$(call inherit-product, $(SRC_TARGET_DIR)/product/generic.mk)
PRODUCT_BRAND := explay
PRODUCT_DEVICE := Alto
PRODUCT_NAME := explay Alto

BOARD_EGL_CFG := device/explay/Alto/egl.cfg

PRODUCT_AAPT_CONFIG :=ldpi mdpi hdpi xhdpi
PRODUCT_AAPT_PREF_CONFIG := hdpi
PRODUCT_CHARACTERISTICS := phone

PRODUCT_COPY_FILES += \
	vendor/explay/Alto/bin:/system/bin \
	vendor/explay/Alto/etc:/system/etc \
	vendor/explay/Alto/lib:/system/lib \
	vendor/explay/Alto/usr:/system/usr \
	vendor/explay/Alto/:/system/ \
	vendor/explay/Alto/bin/6620_launcher:/system/bin/6620_launcher \
	vendor/explay/Alto/bin/6620_wmt_concurrency:/system/bin/6620_wmt_concurrency \
	vendor/explay/Alto/bin/6620_wmt_lpbk:/system/bin/6620_wmt_lpbk \
	vendor/explay/Alto/bin/abcc:/system/bin/abcc \
	vendor/explay/Alto/bin/adb:/system/bin/adb \
	vendor/explay/Alto/bin/aee:/system/bin/aee \
	vendor/explay/Alto/bin/aee_aed:/system/bin/aee_aed \
	vendor/explay/Alto/bin/aee_core_forwarder:/system/bin/aee_core_forwarder \
	vendor/explay/Alto/bin/aee_dumpstate:/system/bin/aee_dumpstate \
	vendor/explay/Alto/bin/akmd8963:/system/bin/akmd8963 \
	vendor/explay/Alto/bin/akmd8975:/system/bin/akmd8975 \
	vendor/explay/Alto/bin/am:/system/bin/am \
	vendor/explay/Alto/bin/ami304d:/system/bin/ami304d \
	vendor/explay/Alto/bin/applypatch:/system/bin/applypatch \
	vendor/explay/Alto/bin/app_process:/system/bin/app_process \
	vendor/explay/Alto/bin/atrace:/system/bin/atrace \
	vendor/explay/Alto/bin/badblocks:/system/bin/badblocks \
	vendor/explay/Alto/bin/batterywarning:/system/bin/batterywarning \
	vendor/explay/Alto/bin/bmgr:/system/bin/bmgr \
	vendor/explay/Alto/bin/bmm050d:/system/bin/bmm050d \
	vendor/explay/Alto/bin/bootanimation:/system/bin/bootanimation \
	vendor/explay/Alto/bin/boot_logo_updater:/system/bin/boot_logo_updater \
	vendor/explay/Alto/bin/btconfig:/system/bin/btconfig \
	vendor/explay/Alto/bin/btlogmask:/system/bin/btlogmask \
	vendor/explay/Alto/bin/bu:/system/bin/bu \
	vendor/explay/Alto/bin/bugmailer.sh:/system/bin/bugmailer.sh \
	vendor/explay/Alto/bin/bugreport:/system/bin/bugreport \
	vendor/explay/Alto/bin/cat:/system/bin/cat \
	vendor/explay/Alto/bin/ccci_fsd:/system/bin/ccci_fsd \
	vendor/explay/Alto/bin/ccci_mdinit:/system/bin/ccci_mdinit \
	vendor/explay/Alto/bin/chmod:/system/bin/chmod \
	vendor/explay/Alto/bin/chown:/system/bin/chown \
	vendor/explay/Alto/bin/cmp:/system/bin/cmp \
	vendor/explay/Alto/bin/content:/system/bin/content \
	vendor/explay/Alto/bin/cp:/system/bin/cp \
	vendor/explay/Alto/bin/dalvikvm:/system/bin/dalvikvm \
	vendor/explay/Alto/bin/date:/system/bin/date \
	vendor/explay/Alto/bin/dbus-daemon:/system/bin/dbus-daemon \
	vendor/explay/Alto/bin/dd:/system/bin/dd \
	vendor/explay/Alto/bin/debuggerd:/system/bin/debuggerd \
	vendor/explay/Alto/bin/dexopt:/system/bin/dexopt \
	vendor/explay/Alto/bin/df:/system/bin/df \
	vendor/explay/Alto/bin/dhcp6c:/system/bin/dhcp6c \
	vendor/explay/Alto/bin/dhcp6ctl:/system/bin/dhcp6ctl \
	vendor/explay/Alto/bin/dhcp6s:/system/bin/dhcp6s \
	vendor/explay/Alto/bin/dhcpcd:/system/bin/dhcpcd \
	vendor/explay/Alto/bin/dm_agent_binder:/system/bin/dm_agent_binder \
	vendor/explay/Alto/bin/dmesg:/system/bin/dmesg \
	vendor/explay/Alto/bin/dnsmasq:/system/bin/dnsmasq \
	vendor/explay/Alto/bin/drmserver:/system/bin/drmserver \
	vendor/explay/Alto/bin/du:/system/bin/du \
	vendor/explay/Alto/bin/dualmdlogger:/system/bin/dualmdlogger \
	vendor/explay/Alto/bin/dumpstate:/system/bin/dumpstate \
	vendor/explay/Alto/bin/dumpsys:/system/bin/dumpsys \
	vendor/explay/Alto/bin/ext4_resize:/system/bin/ext4_resize \
	vendor/explay/Alto/bin/factory:/system/bin/factory \
	vendor/explay/Alto/bin/fsck_msdos:/system/bin/fsck_msdos \
	vendor/explay/Alto/bin/fsck_msdos_mtk:/system/bin/fsck_msdos_mtk \
	vendor/explay/Alto/bin/geomagneticd:/system/bin/geomagneticd \
	vendor/explay/Alto/bin/getevent:/system/bin/getevent \
	vendor/explay/Alto/bin/getprop:/system/bin/getprop \
	vendor/explay/Alto/bin/GoogleOtaBinder:/system/bin/GoogleOtaBinder \
	vendor/explay/Alto/bin/grep:/system/bin/grep \
	vendor/explay/Alto/bin/gsm0710muxd:/system/bin/gsm0710muxd \
	vendor/explay/Alto/bin/gsm0710muxdmd2:/system/bin/gsm0710muxdmd2 \
	vendor/explay/Alto/bin/gzip:/system/bin/gzip \
	vendor/explay/Alto/bin/hald:/system/bin/hald \
	vendor/explay/Alto/bin/hd:/system/bin/hd \
	vendor/explay/Alto/bin/hdc:/system/bin/hdc \
	vendor/explay/Alto/bin/hqftm:/system/bin/hqftm \
	vendor/explay/Alto/bin/id:/system/bin/id \
	vendor/explay/Alto/bin/ifconfig:/system/bin/ifconfig \
	vendor/explay/Alto/bin/iftop:/system/bin/iftop \
	vendor/explay/Alto/bin/ime:/system/bin/ime \
	vendor/explay/Alto/bin/input:/system/bin/input \
	vendor/explay/Alto/bin/insmod:/system/bin/insmod \
	vendor/explay/Alto/bin/installd:/system/bin/installd \
	vendor/explay/Alto/bin/ioctl:/system/bin/ioctl \
	vendor/explay/Alto/bin/ionice:/system/bin/ionice \
	vendor/explay/Alto/bin/ip:/system/bin/ip \
	vendor/explay/Alto/bin/ip6tables:/system/bin/ip6tables \
	vendor/explay/Alto/bin/ipod:/system/bin/ipod \
	vendor/explay/Alto/bin/ipohctl:/system/bin/ipohctl \
	vendor/explay/Alto/bin/iptables:/system/bin/iptables \
	vendor/explay/Alto/bin/keystore:/system/bin/keystore \
	vendor/explay/Alto/bin/kill:/system/bin/kill \
	vendor/explay/Alto/bin/lcdc_screen_cap:/system/bin/lcdc_screen_cap \
	vendor/explay/Alto/bin/linker:/system/bin/linker \
	vendor/explay/Alto/bin/ln:/system/bin/ln \
	vendor/explay/Alto/bin/log:/system/bin/log \
	vendor/explay/Alto/bin/logcat:/system/bin/logcat \
	vendor/explay/Alto/bin/logwrapper:/system/bin/logwrapper \
	vendor/explay/Alto/bin/ls:/system/bin/ls \
	vendor/explay/Alto/bin/lsm303md:/system/bin/lsm303md \
	vendor/explay/Alto/bin/lsmod:/system/bin/lsmod \
	vendor/explay/Alto/bin/lsof:/system/bin/lsof \
	vendor/explay/Alto/bin/magd:/system/bin/magd \
	vendor/explay/Alto/bin/make_ext4fs:/system/bin/make_ext4fs \
	vendor/explay/Alto/bin/matv:/system/bin/matv \
	vendor/explay/Alto/bin/mc6420d:/system/bin/mc6420d \
	vendor/explay/Alto/bin/md5:/system/bin/md5 \
	vendor/explay/Alto/bin/mdlogger:/system/bin/mdlogger \
	vendor/explay/Alto/bin/md_minilog_util:/system/bin/md_minilog_util \
	vendor/explay/Alto/bin/mdnsd:/system/bin/mdnsd \
	vendor/explay/Alto/bin/mediaserver:/system/bin/mediaserver \
	vendor/explay/Alto/bin/memorydumper:/system/bin/memorydumper \
	vendor/explay/Alto/bin/memsicd:/system/bin/memsicd \
	vendor/explay/Alto/bin/memsicd3416x:/system/bin/memsicd3416x \
	vendor/explay/Alto/bin/mfv_ut:/system/bin/mfv_ut \
	vendor/explay/Alto/bin/mkdir:/system/bin/mkdir \
	vendor/explay/Alto/bin/mke2fs:/system/bin/mke2fs \
	vendor/explay/Alto/bin/mksh:/system/bin/mksh \
	vendor/explay/Alto/bin/mobile_log_d:/system/bin/mobile_log_d \
	vendor/explay/Alto/bin/monkey:/system/bin/monkey \
	vendor/explay/Alto/bin/mount:/system/bin/mount \
	vendor/explay/Alto/bin/msensord:/system/bin/msensord \
	vendor/explay/Alto/bin/mtk_agpsd:/system/bin/mtk_agpsd \
	vendor/explay/Alto/bin/mtkbt:/system/bin/mtkbt \
	vendor/explay/Alto/bin/mtpd:/system/bin/mtpd \
	vendor/explay/Alto/bin/muxreport:/system/bin/muxreport \
	vendor/explay/Alto/bin/mv:/system/bin/mv \
	vendor/explay/Alto/bin/nandread:/system/bin/nandread \
	vendor/explay/Alto/bin/ndc:/system/bin/ndc \
	vendor/explay/Alto/bin/netcfg:/system/bin/netcfg \
	vendor/explay/Alto/bin/netd:/system/bin/netd \
	vendor/explay/Alto/bin/netdiag:/system/bin/netdiag \
	vendor/explay/Alto/bin/netstat:/system/bin/netstat \
	vendor/explay/Alto/bin/newfs_msdos:/system/bin/newfs_msdos \
	vendor/explay/Alto/bin/notify:/system/bin/notify \
	vendor/explay/Alto/bin/nvram_agent_binder:/system/bin/nvram_agent_binder \
	vendor/explay/Alto/bin/nvram_daemon:/system/bin/nvram_daemon \
	vendor/explay/Alto/bin/orientationd:/system/bin/orientationd \
	vendor/explay/Alto/bin/permission_check:/system/bin/permission_check \
	vendor/explay/Alto/bin/ping:/system/bin/ping \
	vendor/explay/Alto/bin/pm:/system/bin/pm \
	vendor/explay/Alto/bin/pppd:/system/bin/pppd \
	vendor/explay/Alto/bin/pppd_dt:/system/bin/pppd_dt \
	vendor/explay/Alto/bin/pq:/system/bin/pq \
	vendor/explay/Alto/bin/printenv:/system/bin/printenv \
	vendor/explay/Alto/bin/ps:/system/bin/ps \
	vendor/explay/Alto/bin/racoon:/system/bin/racoon \
	vendor/explay/Alto/bin/radvd:/system/bin/radvd \
	vendor/explay/Alto/bin/reboot:/system/bin/reboot \
	vendor/explay/Alto/bin/renice:/system/bin/renice \
	vendor/explay/Alto/bin/requestsync:/system/bin/requestsync \
	vendor/explay/Alto/bin/resize2fs:/system/bin/resize2fs \
	vendor/explay/Alto/bin/rild:/system/bin/rild \
	vendor/explay/Alto/bin/rildmd2:/system/bin/rildmd2 \
	vendor/explay/Alto/bin/rm:/system/bin/rm \
	vendor/explay/Alto/bin/rmdir:/system/bin/rmdir \
	vendor/explay/Alto/bin/rmmod:/system/bin/rmmod \
	vendor/explay/Alto/bin/route:/system/bin/route \
	vendor/explay/Alto/bin/rtt:/system/bin/rtt \
	vendor/explay/Alto/bin/run-as:/system/bin/run-as \
	vendor/explay/Alto/bin/s62xd:/system/bin/s62xd \
	vendor/explay/Alto/bin/sbchk:/system/bin/sbchk \
	vendor/explay/Alto/bin/schedtest:/system/bin/schedtest \
	vendor/explay/Alto/bin/schedtop:/system/bin/schedtop \
	vendor/explay/Alto/bin/screencap:/system/bin/screencap \
	vendor/explay/Alto/bin/screenshot:/system/bin/screenshot \
	vendor/explay/Alto/bin/sdcard:/system/bin/sdcard \
	vendor/explay/Alto/bin/sdiotool:/system/bin/sdiotool \
	vendor/explay/Alto/bin/send_bug:/system/bin/send_bug \
	vendor/explay/Alto/bin/sendevent:/system/bin/sendevent \
	vendor/explay/Alto/bin/sensorservice:/system/bin/sensorservice \
	vendor/explay/Alto/bin/service:/system/bin/service \
	vendor/explay/Alto/bin/servicemanager:/system/bin/servicemanager \
	vendor/explay/Alto/bin/setconsole:/system/bin/setconsole \
	vendor/explay/Alto/bin/setprop:/system/bin/setprop \
	vendor/explay/Alto/bin/settings:/system/bin/settings \
	vendor/explay/Alto/bin/sh:/system/bin/sh \
	vendor/explay/Alto/bin/shutdown:/system/bin/shutdown \
	vendor/explay/Alto/bin/sleep:/system/bin/sleep \
	vendor/explay/Alto/bin/smd:/system/bin/smd \
	vendor/explay/Alto/bin/sn:/system/bin/sn \
	vendor/explay/Alto/bin/start:/system/bin/start \
	vendor/explay/Alto/bin/stop:/system/bin/stop \
	vendor/explay/Alto/bin/superumount:/system/bin/superumount \
	vendor/explay/Alto/bin/surfaceflinger:/system/bin/surfaceflinger \
	vendor/explay/Alto/bin/svc:/system/bin/svc \
	vendor/explay/Alto/bin/sync:/system/bin/sync \
	vendor/explay/Alto/bin/system_server:/system/bin/system_server \
	vendor/explay/Alto/bin/tc:/system/bin/tc \
	vendor/explay/Alto/bin/thermal:/system/bin/thermal \
	vendor/explay/Alto/bin/thermald:/system/bin/thermald \
	vendor/explay/Alto/bin/thermal_manager:/system/bin/thermal_manager \
	vendor/explay/Alto/bin/tiny_mkswap:/system/bin/tiny_mkswap \
	vendor/explay/Alto/bin/tiny_swapoff:/system/bin/tiny_swapoff \
	vendor/explay/Alto/bin/tiny_swapon:/system/bin/tiny_swapon \
	vendor/explay/Alto/bin/toolbox:/system/bin/toolbox \
	vendor/explay/Alto/bin/top:/system/bin/top \
	vendor/explay/Alto/bin/touch:/system/bin/touch \
	vendor/explay/Alto/bin/uiautomator:/system/bin/uiautomator \
	vendor/explay/Alto/bin/umount:/system/bin/umount \
	vendor/explay/Alto/bin/uptime:/system/bin/uptime \
	vendor/explay/Alto/bin/vdc:/system/bin/vdc \
	vendor/explay/Alto/bin/vmstat:/system/bin/vmstat \
	vendor/explay/Alto/bin/vold:/system/bin/vold \
	vendor/explay/Alto/bin/vtservice:/system/bin/vtservice \
	vendor/explay/Alto/bin/watchprops:/system/bin/watchprops \
	vendor/explay/Alto/bin/wipe:/system/bin/wipe \
	vendor/explay/Alto/bin/wlan_loader:/system/bin/wlan_loader \
	vendor/explay/Alto/bin/wpa_supplicant:/system/bin/wpa_supplicant \
	vendor/explay/Alto/bin/xlog:/system/bin/xlog \
	vendor/explay/Alto/bin/:/system/bin/ \
	vendor/explay/Alto/etc/agps_profiles_conf.xml:/system/etc/agps_profiles_conf.xml \
	vendor/explay/Alto/etc/apns-conf.xml:/system/etc/apns-conf.xml \
	vendor/explay/Alto/etc/audio_effects.conf:/system/etc/audio_effects.conf \
	vendor/explay/Alto/etc/audio_policy.conf:/system/etc/audio_policy.conf \
	vendor/explay/Alto/etc/bluetooth:/system/etc/bluetooth \
	vendor/explay/Alto/etc/custom.conf:/system/etc/custom.conf \
	vendor/explay/Alto/etc/dbus.conf:/system/etc/dbus.conf \
	vendor/explay/Alto/etc/dhcpcd:/system/etc/dhcpcd \
	vendor/explay/Alto/etc/disableapplist.txt:/system/etc/disableapplist.txt \
	vendor/explay/Alto/etc/drm_chmod:/system/etc/drm_chmod \
	vendor/explay/Alto/etc/epo_conf.xml:/system/etc/epo_conf.xml \
	vendor/explay/Alto/etc/event-log-tags:/system/etc/event-log-tags \
	vendor/explay/Alto/etc/factory.ini:/system/etc/factory.ini \
	vendor/explay/Alto/etc/fallback_fonts.xml:/system/etc/fallback_fonts.xml \
	vendor/explay/Alto/etc/firmware:/system/etc/firmware \
	vendor/explay/Alto/etc/fmr:/system/etc/fmr \
	vendor/explay/Alto/etc/geocoding.db:/system/etc/geocoding.db \
	vendor/explay/Alto/etc/g.prop:/system/etc/g.prop \
	vendor/explay/Alto/etc/hosts:/system/etc/hosts \
	vendor/explay/Alto/etc/hq_ftm.xml:/system/etc/hq_ftm.xml \
	vendor/explay/Alto/etc/init.goldfish.sh:/system/etc/init.goldfish.sh \
	vendor/explay/Alto/etc/media_codecs.xml:/system/etc/media_codecs.xml \
	vendor/explay/Alto/etc/mkshrc:/system/etc/mkshrc \
	vendor/explay/Alto/etc/mtklog-config.prop:/system/etc/mtklog-config.prop \
	vendor/explay/Alto/etc/mtk_omx_core.cfg:/system/etc/mtk_omx_core.cfg \
	vendor/explay/Alto/etc/NOTICE:/system/etc/NOTICE \
	vendor/explay/Alto/etc/NOTICE.html.gz:/system/etc/NOTICE.html.gz \
	vendor/explay/Alto/etc/partition_permission.sh:/system/etc/partition_permission.sh \
	vendor/explay/Alto/etc/permissions:/system/etc/permissions \
	vendor/explay/Alto/etc/player.cfg:/system/etc/player.cfg \
	vendor/explay/Alto/etc/ppp:/system/etc/ppp \
	vendor/explay/Alto/etc/preferred-apps:/system/etc/preferred-apps \
	vendor/explay/Alto/etc/radvd:/system/etc/radvd \
	vendor/explay/Alto/etc/recovery-resource.dat:/system/etc/recovery-resource.dat \
	vendor/explay/Alto/etc/resmonwhitelist.txt:/system/etc/resmonwhitelist.txt \
	vendor/explay/Alto/etc/ril:/system/etc/ril \
	vendor/explay/Alto/etc/security:/system/etc/security \
	vendor/explay/Alto/etc/spn-conf.xml:/system/etc/spn-conf.xml \
	vendor/explay/Alto/etc/system_fonts.xml:/system/etc/system_fonts.xml \
	vendor/explay/Alto/etc/theme:/system/etc/theme \
	vendor/explay/Alto/etc/throttle.sh:/system/etc/throttle.sh \
	vendor/explay/Alto/etc/virtual-spn-conf-by-efpnn.xml:/system/etc/virtual-spn-conf-by-efpnn.xml \
	vendor/explay/Alto/etc/virtual-spn-conf-by-efspn.xml:/system/etc/virtual-spn-conf-by-efspn.xml \
	vendor/explay/Alto/etc/virtual-spn-conf-by-imsi.xml:/system/etc/virtual-spn-conf-by-imsi.xml \
	vendor/explay/Alto/etc/voicecommand:/system/etc/voicecommand \
	vendor/explay/Alto/etc/vold.fstab:/system/etc/vold.fstab \
	vendor/explay/Alto/etc/vold.fstab.fat.nand:/system/etc/vold.fstab.fat.nand \
	vendor/explay/Alto/etc/vold.fstab.nand:/system/etc/vold.fstab.nand \
	vendor/explay/Alto/etc/wide-dhcpv6:/system/etc/wide-dhcpv6 \
	vendor/explay/Alto/etc/wifi:/system/etc/wifi \
	vendor/explay/Alto/etc/xlog-filter-default:/system/etc/xlog-filter-default \
	vendor/explay/Alto/etc/xlog-filter-tags:/system/etc/xlog-filter-tags \
	vendor/explay/Alto/etc/:/system/etc/ \
	vendor/explay/Alto/etc/bluetooth/audio.conf:/system/etc/bluetooth/audio.conf \
	vendor/explay/Alto/etc/bluetooth/auto_pairing.conf:/system/etc/bluetooth/auto_pairing.conf \
	vendor/explay/Alto/etc/bluetooth/blacklist.conf:/system/etc/bluetooth/blacklist.conf \
	vendor/explay/Alto/etc/bluetooth/input.conf:/system/etc/bluetooth/input.conf \
	vendor/explay/Alto/etc/bluetooth/network.conf:/system/etc/bluetooth/network.conf \
	vendor/explay/Alto/etc/bluetooth/:/system/etc/bluetooth/ \
	vendor/explay/Alto/etc/dhcpcd/dhcpcd-hooks:/system/etc/dhcpcd/dhcpcd-hooks \
	vendor/explay/Alto/etc/dhcpcd/dhcpcd-run-hooks:/system/etc/dhcpcd/dhcpcd-run-hooks \
	vendor/explay/Alto/etc/dhcpcd/:/system/etc/dhcpcd/ \
	vendor/explay/Alto/etc/dhcpcd/dhcpcd-hooks/20-dns.conf:/system/etc/dhcpcd/dhcpcd-hooks/20-dns.conf \
	vendor/explay/Alto/etc/dhcpcd/dhcpcd-hooks/95-configured:/system/etc/dhcpcd/dhcpcd-hooks/95-configured \
	vendor/explay/Alto/etc/dhcpcd/dhcpcd-hooks/:/system/etc/dhcpcd/dhcpcd-hooks/ \
	vendor/explay/Alto/etc/firmware/catcher_filter_1_wg_n.bin:/system/etc/firmware/catcher_filter_1_wg_n.bin \
	vendor/explay/Alto/etc/firmware/modem_1_wg_n.img:/system/etc/firmware/modem_1_wg_n.img \
	vendor/explay/Alto/etc/firmware/mt6572_82_patch_e1_0_hdr.bin:/system/etc/firmware/mt6572_82_patch_e1_0_hdr.bin \
	vendor/explay/Alto/etc/firmware/mt6572_82_patch_e1_1_hdr.bin:/system/etc/firmware/mt6572_82_patch_e1_1_hdr.bin \
	vendor/explay/Alto/etc/firmware/mt6627:/system/etc/firmware/mt6627 \
	vendor/explay/Alto/etc/firmware/S_ANDRO_SFL.ini:/system/etc/firmware/S_ANDRO_SFL.ini \
	vendor/explay/Alto/etc/firmware/WIFI_RAM_CODE:/system/etc/firmware/WIFI_RAM_CODE \
	vendor/explay/Alto/etc/firmware/WIFI_RAM_CODE_E6:/system/etc/firmware/WIFI_RAM_CODE_E6 \
	vendor/explay/Alto/etc/firmware/WIFI_RAM_CODE_MT6582:/system/etc/firmware/WIFI_RAM_CODE_MT6582 \
	vendor/explay/Alto/etc/firmware/WIFI_RAM_CODE_MT6628:/system/etc/firmware/WIFI_RAM_CODE_MT6628 \
	vendor/explay/Alto/etc/firmware/WMT_SOC.cfg:/system/etc/firmware/WMT_SOC.cfg \
	vendor/explay/Alto/etc/firmware/:/system/etc/firmware/ \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:/system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:/system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:/system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:/system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:/system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:/system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:/system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:/system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:/system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
	vendor/explay/Alto/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:/system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
	vendor/explay/Alto/etc/firmware/mt6627/:/system/etc/firmware/mt6627/ \
	vendor/explay/Alto/etc/fmr/mt6627_fm_cust.cfg:/system/etc/fmr/mt6627_fm_cust.cfg \
	vendor/explay/Alto/etc/fmr/:/system/etc/fmr/ \
	vendor/explay/Alto/etc/permissions/android.hardware.bluetooth.xml:/system/etc/permissions/android.hardware.bluetooth.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.camera.xml:/system/etc/permissions/android.hardware.camera.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.faketouch.xml:/system/etc/permissions/android.hardware.faketouch.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.location.gps.xml:/system/etc/permissions/android.hardware.location.gps.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.microphone.xml:/system/etc/permissions/android.hardware.microphone.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.sensor.accelerometer.xml:/system/etc/permissions/android.hardware.sensor.accelerometer.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.sensor.compass.xml:/system/etc/permissions/android.hardware.sensor.compass.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.sensor.light.xml:/system/etc/permissions/android.hardware.sensor.light.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.sensor.proximity.xml:/system/etc/permissions/android.hardware.sensor.proximity.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.telephony.gsm.xml:/system/etc/permissions/android.hardware.telephony.gsm.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml:/system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:/system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.touchscreen.multitouch.xml:/system/etc/permissions/android.hardware.touchscreen.multitouch.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.touchscreen.xml:/system/etc/permissions/android.hardware.touchscreen.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.usb.accessory.xml:/system/etc/permissions/android.hardware.usb.accessory.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.usb.host.xml:/system/etc/permissions/android.hardware.usb.host.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.wifi.direct.xml:/system/etc/permissions/android.hardware.wifi.direct.xml \
	vendor/explay/Alto/etc/permissions/android.hardware.wifi.xml:/system/etc/permissions/android.hardware.wifi.xml \
	vendor/explay/Alto/etc/permissions/android.software.live_wallpaper.xml:/system/etc/permissions/android.software.live_wallpaper.xml \
	vendor/explay/Alto/etc/permissions/android.software.sip.voip.xml:/system/etc/permissions/android.software.sip.voip.xml \
	vendor/explay/Alto/etc/permissions/android.software.sip.xml:/system/etc/permissions/android.software.sip.xml \
	vendor/explay/Alto/etc/permissions/com.android.location.provider.xml:/system/etc/permissions/com.android.location.provider.xml \
	vendor/explay/Alto/etc/permissions/com.google.android.maps.xml:/system/etc/permissions/com.google.android.maps.xml \
	vendor/explay/Alto/etc/permissions/com.google.android.media.effects.xml:/system/etc/permissions/com.google.android.media.effects.xml \
	vendor/explay/Alto/etc/permissions/com.google.widevine.software.drm.xml:/system/etc/permissions/com.google.widevine.software.drm.xml \
	vendor/explay/Alto/etc/permissions/features.xml:/system/etc/permissions/features.xml \
	vendor/explay/Alto/etc/permissions/handheld_core_hardware.xml:/system/etc/permissions/handheld_core_hardware.xml \
	vendor/explay/Alto/etc/permissions/hq_ftm.xml:/system/etc/permissions/hq_ftm.xml \
	vendor/explay/Alto/etc/permissions/media_codecs.xml:/system/etc/permissions/media_codecs.xml \
	vendor/explay/Alto/etc/permissions/platform.xml:/system/etc/permissions/platform.xml \
	vendor/explay/Alto/etc/permissions/:/system/etc/permissions/ \
	vendor/explay/Alto/etc/ppp/ip-up-vpn:/system/etc/ppp/ip-up-vpn \
	vendor/explay/Alto/etc/ppp/:/system/etc/ppp/ \
	vendor/explay/Alto/etc/preferred-apps/google.xml:/system/etc/preferred-apps/google.xml \
	vendor/explay/Alto/etc/preferred-apps/:/system/etc/preferred-apps/ \
	vendor/explay/Alto/etc/radvd/radvd.conf:/system/etc/radvd/radvd.conf \
	vendor/explay/Alto/etc/radvd/:/system/etc/radvd/ \
	vendor/explay/Alto/etc/ril/oper.lis:/system/etc/ril/oper.lis \
	vendor/explay/Alto/etc/ril/:/system/etc/ril/ \
	vendor/explay/Alto/etc/security/cacerts:/system/etc/security/cacerts \
	vendor/explay/Alto/etc/security/otacerts.zip:/system/etc/security/otacerts.zip \
	vendor/explay/Alto/etc/security/:/system/etc/security/ \
	vendor/explay/Alto/etc/security/cacerts/00673b5b.0:/system/etc/security/cacerts/00673b5b.0 \
	vendor/explay/Alto/etc/security/cacerts/03e16f6c.0:/system/etc/security/cacerts/03e16f6c.0 \
	vendor/explay/Alto/etc/security/cacerts/08aef7bb.0:/system/etc/security/cacerts/08aef7bb.0 \
	vendor/explay/Alto/etc/security/cacerts/0d188d89.0:/system/etc/security/cacerts/0d188d89.0 \
	vendor/explay/Alto/etc/security/cacerts/10531352.0:/system/etc/security/cacerts/10531352.0 \
	vendor/explay/Alto/etc/security/cacerts/111e6273.0:/system/etc/security/cacerts/111e6273.0 \
	vendor/explay/Alto/etc/security/cacerts/1155c94b.0:/system/etc/security/cacerts/1155c94b.0 \
	vendor/explay/Alto/etc/security/cacerts/119afc2e.0:/system/etc/security/cacerts/119afc2e.0 \
	vendor/explay/Alto/etc/security/cacerts/11a09b38.0:/system/etc/security/cacerts/11a09b38.0 \
	vendor/explay/Alto/etc/security/cacerts/12d55845.0:/system/etc/security/cacerts/12d55845.0 \
	vendor/explay/Alto/etc/security/cacerts/17b51fe6.0:/system/etc/security/cacerts/17b51fe6.0 \
	vendor/explay/Alto/etc/security/cacerts/1920cacb.0:/system/etc/security/cacerts/1920cacb.0 \
	vendor/explay/Alto/etc/security/cacerts/1dac3003.0:/system/etc/security/cacerts/1dac3003.0 \
	vendor/explay/Alto/etc/security/cacerts/1dbdda5b.0:/system/etc/security/cacerts/1dbdda5b.0 \
	vendor/explay/Alto/etc/security/cacerts/1dcd6f4c.0:/system/etc/security/cacerts/1dcd6f4c.0 \
	vendor/explay/Alto/etc/security/cacerts/1df5ec47.0:/system/etc/security/cacerts/1df5ec47.0 \
	vendor/explay/Alto/etc/security/cacerts/1e1eab7c.0:/system/etc/security/cacerts/1e1eab7c.0 \
	vendor/explay/Alto/etc/security/cacerts/1e8e7201.0:/system/etc/security/cacerts/1e8e7201.0 \
	vendor/explay/Alto/etc/security/cacerts/1eb37bdf.0:/system/etc/security/cacerts/1eb37bdf.0 \
	vendor/explay/Alto/etc/security/cacerts/219d9499.0:/system/etc/security/cacerts/219d9499.0 \
	vendor/explay/Alto/etc/security/cacerts/23f4c490.0:/system/etc/security/cacerts/23f4c490.0 \
	vendor/explay/Alto/etc/security/cacerts/27af790d.0:/system/etc/security/cacerts/27af790d.0 \
	vendor/explay/Alto/etc/security/cacerts/2afc57aa.0:/system/etc/security/cacerts/2afc57aa.0 \
	vendor/explay/Alto/etc/security/cacerts/2e8714cb.0:/system/etc/security/cacerts/2e8714cb.0 \
	vendor/explay/Alto/etc/security/cacerts/2fa87019.0:/system/etc/security/cacerts/2fa87019.0 \
	vendor/explay/Alto/etc/security/cacerts/2fb1850a.0:/system/etc/security/cacerts/2fb1850a.0 \
	vendor/explay/Alto/etc/security/cacerts/33815e15.0:/system/etc/security/cacerts/33815e15.0 \
	vendor/explay/Alto/etc/security/cacerts/343eb6cb.0:/system/etc/security/cacerts/343eb6cb.0 \
	vendor/explay/Alto/etc/security/cacerts/399e7759.0:/system/etc/security/cacerts/399e7759.0 \
	vendor/explay/Alto/etc/security/cacerts/3a3b02ce.0:/system/etc/security/cacerts/3a3b02ce.0 \
	vendor/explay/Alto/etc/security/cacerts/3ad48a91.0:/system/etc/security/cacerts/3ad48a91.0 \
	vendor/explay/Alto/etc/security/cacerts/3c58f906.0:/system/etc/security/cacerts/3c58f906.0 \
	vendor/explay/Alto/etc/security/cacerts/3c860d51.0:/system/etc/security/cacerts/3c860d51.0 \
	vendor/explay/Alto/etc/security/cacerts/3d441de8.0:/system/etc/security/cacerts/3d441de8.0 \
	vendor/explay/Alto/etc/security/cacerts/3e7271e8.0:/system/etc/security/cacerts/3e7271e8.0 \
	vendor/explay/Alto/etc/security/cacerts/418595b9.0:/system/etc/security/cacerts/418595b9.0 \
	vendor/explay/Alto/etc/security/cacerts/455f1b52.0:/system/etc/security/cacerts/455f1b52.0 \
	vendor/explay/Alto/etc/security/cacerts/46b2fd3b.0:/system/etc/security/cacerts/46b2fd3b.0 \
	vendor/explay/Alto/etc/security/cacerts/48478734.0:/system/etc/security/cacerts/48478734.0 \
	vendor/explay/Alto/etc/security/cacerts/4d654d1d.0:/system/etc/security/cacerts/4d654d1d.0 \
	vendor/explay/Alto/etc/security/cacerts/4e18c148.0:/system/etc/security/cacerts/4e18c148.0 \
	vendor/explay/Alto/etc/security/cacerts/4fbd6bfa.0:/system/etc/security/cacerts/4fbd6bfa.0 \
	vendor/explay/Alto/etc/security/cacerts/5021a0a2.0:/system/etc/security/cacerts/5021a0a2.0 \
	vendor/explay/Alto/etc/security/cacerts/5046c355.0:/system/etc/security/cacerts/5046c355.0 \
	vendor/explay/Alto/etc/security/cacerts/524d9b43.0:/system/etc/security/cacerts/524d9b43.0 \
	vendor/explay/Alto/etc/security/cacerts/56b8a0b6.0:/system/etc/security/cacerts/56b8a0b6.0 \
	vendor/explay/Alto/etc/security/cacerts/57692373.0:/system/etc/security/cacerts/57692373.0 \
	vendor/explay/Alto/etc/security/cacerts/58a44af1.0:/system/etc/security/cacerts/58a44af1.0 \
	vendor/explay/Alto/etc/security/cacerts/594f1775.0:/system/etc/security/cacerts/594f1775.0 \
	vendor/explay/Alto/etc/security/cacerts/5a3f0ff8.0:/system/etc/security/cacerts/5a3f0ff8.0 \
	vendor/explay/Alto/etc/security/cacerts/5a5372fc.0:/system/etc/security/cacerts/5a5372fc.0 \
	vendor/explay/Alto/etc/security/cacerts/5cf9d536.0:/system/etc/security/cacerts/5cf9d536.0 \
	vendor/explay/Alto/etc/security/cacerts/5e4e69e7.0:/system/etc/security/cacerts/5e4e69e7.0 \
	vendor/explay/Alto/etc/security/cacerts/60afe812.0:/system/etc/security/cacerts/60afe812.0 \
	vendor/explay/Alto/etc/security/cacerts/635ccfd5.0:/system/etc/security/cacerts/635ccfd5.0 \
	vendor/explay/Alto/etc/security/cacerts/67495436.0:/system/etc/security/cacerts/67495436.0 \
	vendor/explay/Alto/etc/security/cacerts/69105f4f.0:/system/etc/security/cacerts/69105f4f.0 \
	vendor/explay/Alto/etc/security/cacerts/6adf0799.0:/system/etc/security/cacerts/6adf0799.0 \
	vendor/explay/Alto/etc/security/cacerts/6e8bf996.0:/system/etc/security/cacerts/6e8bf996.0 \
	vendor/explay/Alto/etc/security/cacerts/6fcc125d.0:/system/etc/security/cacerts/6fcc125d.0 \
	vendor/explay/Alto/etc/security/cacerts/72f369af.0:/system/etc/security/cacerts/72f369af.0 \
	vendor/explay/Alto/etc/security/cacerts/72fa7371.0:/system/etc/security/cacerts/72fa7371.0 \
	vendor/explay/Alto/etc/security/cacerts/74c26bd0.0:/system/etc/security/cacerts/74c26bd0.0 \
	vendor/explay/Alto/etc/security/cacerts/75680d2e.0:/system/etc/security/cacerts/75680d2e.0 \
	vendor/explay/Alto/etc/security/cacerts/7651b327.0:/system/etc/security/cacerts/7651b327.0 \
	vendor/explay/Alto/etc/security/cacerts/76579174.0:/system/etc/security/cacerts/76579174.0 \
	vendor/explay/Alto/etc/security/cacerts/7672ac4b.0:/system/etc/security/cacerts/7672ac4b.0 \
	vendor/explay/Alto/etc/security/cacerts/7999be0d.0:/system/etc/security/cacerts/7999be0d.0 \
	vendor/explay/Alto/etc/security/cacerts/7a481e66.0:/system/etc/security/cacerts/7a481e66.0 \
	vendor/explay/Alto/etc/security/cacerts/7a819ef2.0:/system/etc/security/cacerts/7a819ef2.0 \
	vendor/explay/Alto/etc/security/cacerts/7d3cd826.0:/system/etc/security/cacerts/7d3cd826.0 \
	vendor/explay/Alto/etc/security/cacerts/7d453d8f.0:/system/etc/security/cacerts/7d453d8f.0 \
	vendor/explay/Alto/etc/security/cacerts/81b9768f.0:/system/etc/security/cacerts/81b9768f.0 \
	vendor/explay/Alto/etc/security/cacerts/8470719d.0:/system/etc/security/cacerts/8470719d.0 \
	vendor/explay/Alto/etc/security/cacerts/84cba82f.0:/system/etc/security/cacerts/84cba82f.0 \
	vendor/explay/Alto/etc/security/cacerts/85cde254.0:/system/etc/security/cacerts/85cde254.0 \
	vendor/explay/Alto/etc/security/cacerts/86212b19.0:/system/etc/security/cacerts/86212b19.0 \
	vendor/explay/Alto/etc/security/cacerts/87753b0d.0:/system/etc/security/cacerts/87753b0d.0 \
	vendor/explay/Alto/etc/security/cacerts/882de061.0:/system/etc/security/cacerts/882de061.0 \
	vendor/explay/Alto/etc/security/cacerts/895cad1a.0:/system/etc/security/cacerts/895cad1a.0 \
	vendor/explay/Alto/etc/security/cacerts/89c02a45.0:/system/etc/security/cacerts/89c02a45.0 \
	vendor/explay/Alto/etc/security/cacerts/8f7b96c4.0:/system/etc/security/cacerts/8f7b96c4.0 \
	vendor/explay/Alto/etc/security/cacerts/9339512a.0:/system/etc/security/cacerts/9339512a.0 \
	vendor/explay/Alto/etc/security/cacerts/95aff9e3.0:/system/etc/security/cacerts/95aff9e3.0 \
	vendor/explay/Alto/etc/security/cacerts/9685a493.0:/system/etc/security/cacerts/9685a493.0 \
	vendor/explay/Alto/etc/security/cacerts/9772ca32.0:/system/etc/security/cacerts/9772ca32.0 \
	vendor/explay/Alto/etc/security/cacerts/9d6523ce.0:/system/etc/security/cacerts/9d6523ce.0 \
	vendor/explay/Alto/etc/security/cacerts/9dbefe7b.0:/system/etc/security/cacerts/9dbefe7b.0 \
	vendor/explay/Alto/etc/security/cacerts/9f533518.0:/system/etc/security/cacerts/9f533518.0 \
	vendor/explay/Alto/etc/security/cacerts/a0bc6fbb.0:/system/etc/security/cacerts/a0bc6fbb.0 \
	vendor/explay/Alto/etc/security/cacerts/a15b3b6b.0:/system/etc/security/cacerts/a15b3b6b.0 \
	vendor/explay/Alto/etc/security/cacerts/a3896b44.0:/system/etc/security/cacerts/a3896b44.0 \
	vendor/explay/Alto/etc/security/cacerts/a7605362.0:/system/etc/security/cacerts/a7605362.0 \
	vendor/explay/Alto/etc/security/cacerts/a7d2cf64.0:/system/etc/security/cacerts/a7d2cf64.0 \
	vendor/explay/Alto/etc/security/cacerts/ab5346f4.0:/system/etc/security/cacerts/ab5346f4.0 \
	vendor/explay/Alto/etc/security/cacerts/add67345.0:/system/etc/security/cacerts/add67345.0 \
	vendor/explay/Alto/etc/security/cacerts/aeb67534.0:/system/etc/security/cacerts/aeb67534.0 \
	vendor/explay/Alto/etc/security/cacerts/b0f3e76e.0:/system/etc/security/cacerts/b0f3e76e.0 \
	vendor/explay/Alto/etc/security/cacerts/b7db1890.0:/system/etc/security/cacerts/b7db1890.0 \
	vendor/explay/Alto/etc/security/cacerts/bc3f2570.0:/system/etc/security/cacerts/bc3f2570.0 \
	vendor/explay/Alto/etc/security/cacerts/bcdd5959.0:/system/etc/security/cacerts/bcdd5959.0 \
	vendor/explay/Alto/etc/security/cacerts/bda4cc84.0:/system/etc/security/cacerts/bda4cc84.0 \
	vendor/explay/Alto/etc/security/cacerts/bdacca6f.0:/system/etc/security/cacerts/bdacca6f.0 \
	vendor/explay/Alto/etc/security/cacerts/bf64f35b.0:/system/etc/security/cacerts/bf64f35b.0 \
	vendor/explay/Alto/etc/security/cacerts/c215bc69.0:/system/etc/security/cacerts/c215bc69.0 \
	vendor/explay/Alto/etc/security/cacerts/c33a80d4.0:/system/etc/security/cacerts/c33a80d4.0 \
	vendor/explay/Alto/etc/security/cacerts/c3a6a9ad.0:/system/etc/security/cacerts/c3a6a9ad.0 \
	vendor/explay/Alto/etc/security/cacerts/c527e4ab.0:/system/etc/security/cacerts/c527e4ab.0 \
	vendor/explay/Alto/etc/security/cacerts/c7e2a638.0:/system/etc/security/cacerts/c7e2a638.0 \
	vendor/explay/Alto/etc/security/cacerts/c8763593.0:/system/etc/security/cacerts/c8763593.0 \
	vendor/explay/Alto/etc/security/cacerts/ccc52f49.0:/system/etc/security/cacerts/ccc52f49.0 \
	vendor/explay/Alto/etc/security/cacerts/cdaebb72.0:/system/etc/security/cacerts/cdaebb72.0 \
	vendor/explay/Alto/etc/security/cacerts/cf701eeb.0:/system/etc/security/cacerts/cf701eeb.0 \
	vendor/explay/Alto/etc/security/cacerts/d16a5865.0:/system/etc/security/cacerts/d16a5865.0 \
	vendor/explay/Alto/etc/security/cacerts/d537fba6.0:/system/etc/security/cacerts/d537fba6.0 \
	vendor/explay/Alto/etc/security/cacerts/d59297b8.0:/system/etc/security/cacerts/d59297b8.0 \
	vendor/explay/Alto/etc/security/cacerts/d64f06f3.0:/system/etc/security/cacerts/d64f06f3.0 \
	vendor/explay/Alto/etc/security/cacerts/d777342d.0:/system/etc/security/cacerts/d777342d.0 \
	vendor/explay/Alto/etc/security/cacerts/d8274e24.0:/system/etc/security/cacerts/d8274e24.0 \
	vendor/explay/Alto/etc/security/cacerts/dbc54cab.0:/system/etc/security/cacerts/dbc54cab.0 \
	vendor/explay/Alto/etc/security/cacerts/ddc328ff.0:/system/etc/security/cacerts/ddc328ff.0 \
	vendor/explay/Alto/etc/security/cacerts/e48193cf.0:/system/etc/security/cacerts/e48193cf.0 \
	vendor/explay/Alto/etc/security/cacerts/e60bf0c0.0:/system/etc/security/cacerts/e60bf0c0.0 \
	vendor/explay/Alto/etc/security/cacerts/e775ed2d.0:/system/etc/security/cacerts/e775ed2d.0 \
	vendor/explay/Alto/etc/security/cacerts/e7b8d656.0:/system/etc/security/cacerts/e7b8d656.0 \
	vendor/explay/Alto/etc/security/cacerts/e8651083.0:/system/etc/security/cacerts/e8651083.0 \
	vendor/explay/Alto/etc/security/cacerts/ea169617.0:/system/etc/security/cacerts/ea169617.0 \
	vendor/explay/Alto/etc/security/cacerts/eb375c3e.0:/system/etc/security/cacerts/eb375c3e.0 \
	vendor/explay/Alto/etc/security/cacerts/ed049835.0:/system/etc/security/cacerts/ed049835.0 \
	vendor/explay/Alto/etc/security/cacerts/ed524cf5.0:/system/etc/security/cacerts/ed524cf5.0 \
	vendor/explay/Alto/etc/security/cacerts/ee7cd6fb.0:/system/etc/security/cacerts/ee7cd6fb.0 \
	vendor/explay/Alto/etc/security/cacerts/f4996e82.0:/system/etc/security/cacerts/f4996e82.0 \
	vendor/explay/Alto/etc/security/cacerts/f58a60fe.0:/system/etc/security/cacerts/f58a60fe.0 \
	vendor/explay/Alto/etc/security/cacerts/f61bff45.0:/system/etc/security/cacerts/f61bff45.0 \
	vendor/explay/Alto/etc/security/cacerts/f80cc7f6.0:/system/etc/security/cacerts/f80cc7f6.0 \
	vendor/explay/Alto/etc/security/cacerts/fac084d7.0:/system/etc/security/cacerts/fac084d7.0 \
	vendor/explay/Alto/etc/security/cacerts/facacbc6.0:/system/etc/security/cacerts/facacbc6.0 \
	vendor/explay/Alto/etc/security/cacerts/fb126c6d.0:/system/etc/security/cacerts/fb126c6d.0 \
	vendor/explay/Alto/etc/security/cacerts/fde84897.0:/system/etc/security/cacerts/fde84897.0 \
	vendor/explay/Alto/etc/security/cacerts/ff783690.0:/system/etc/security/cacerts/ff783690.0 \
	vendor/explay/Alto/etc/security/cacerts/:/system/etc/security/cacerts/ \
	vendor/explay/Alto/etc/theme/thememap.xml:/system/etc/theme/thememap.xml \
	vendor/explay/Alto/etc/theme/:/system/etc/theme/ \
	vendor/explay/Alto/etc/voicecommand/keyword:/system/etc/voicecommand/keyword \
	vendor/explay/Alto/etc/voicecommand/training:/system/etc/voicecommand/training \
	vendor/explay/Alto/etc/voicecommand/voiceui:/system/etc/voicecommand/voiceui \
	vendor/explay/Alto/etc/voicecommand/:/system/etc/voicecommand/ \
	vendor/explay/Alto/etc/voicecommand/keyword/1.xml:/system/etc/voicecommand/keyword/1.xml \
	vendor/explay/Alto/etc/voicecommand/keyword/2.xml:/system/etc/voicecommand/keyword/2.xml \
	vendor/explay/Alto/etc/voicecommand/keyword/3.xml:/system/etc/voicecommand/keyword/3.xml \
	vendor/explay/Alto/etc/voicecommand/keyword/:/system/etc/voicecommand/keyword/ \
	vendor/explay/Alto/etc/voicecommand/training/ubmfile:/system/etc/voicecommand/training/ubmfile \
	vendor/explay/Alto/etc/voicecommand/training/:/system/etc/voicecommand/training/ \
	vendor/explay/Alto/etc/voicecommand/training/ubmfile/128.dat:/system/etc/voicecommand/training/ubmfile/128.dat \
	vendor/explay/Alto/etc/voicecommand/training/ubmfile/64.dat:/system/etc/voicecommand/training/ubmfile/64.dat \
	vendor/explay/Alto/etc/voicecommand/training/ubmfile/:/system/etc/voicecommand/training/ubmfile/ \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile:/system/etc/voicecommand/voiceui/modefile \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern:/system/etc/voicecommand/voiceui/uipattern \
	vendor/explay/Alto/etc/voicecommand/voiceui/:/system/etc/voicecommand/voiceui/ \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/command_3and23.dic:/system/etc/voicecommand/voiceui/modefile/command_3and23.dic \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/command_6and23.dic:/system/etc/voicecommand/voiceui/modefile/command_6and23.dic \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/commandfilr2.dic:/system/etc/voicecommand/voiceui/modefile/commandfilr2.dic \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/commandfilr.dic:/system/etc/voicecommand/voiceui/modefile/commandfilr.dic \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/command_only23.dic:/system/etc/voicecommand/voiceui/modefile/command_only23.dic \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/GMMModel1.bin:/system/etc/voicecommand/voiceui/modefile/GMMModel1.bin \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/GMMModel2.bin:/system/etc/voicecommand/voiceui/modefile/GMMModel2.bin \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/GMMModel3.bin:/system/etc/voicecommand/voiceui/modefile/GMMModel3.bin \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/Model1.bin:/system/etc/voicecommand/voiceui/modefile/Model1.bin \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/Model2.bin:/system/etc/voicecommand/voiceui/modefile/Model2.bin \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/Model3.bin:/system/etc/voicecommand/voiceui/modefile/Model3.bin \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/Model_M_gmmfea39d.dat:/system/etc/voicecommand/voiceui/modefile/Model_M_gmmfea39d.dat \
	vendor/explay/Alto/etc/voicecommand/voiceui/modefile/:/system/etc/voicecommand/voiceui/modefile/ \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/Chinese-Mandarin:/system/etc/voicecommand/voiceui/uipattern/Chinese-Mandarin \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/Chinese-Taiwan:/system/etc/voicecommand/voiceui/uipattern/Chinese-Taiwan \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/English:/system/etc/voicecommand/voiceui/uipattern/English \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/:/system/etc/voicecommand/voiceui/uipattern/ \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/Chinese-Mandarin/cmd_pattern:/system/etc/voicecommand/voiceui/uipattern/Chinese-Mandarin/cmd_pattern \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/Chinese-Mandarin/:/system/etc/voicecommand/voiceui/uipattern/Chinese-Mandarin/ \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/Chinese-Taiwan/cmd_pattern:/system/etc/voicecommand/voiceui/uipattern/Chinese-Taiwan/cmd_pattern \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/Chinese-Taiwan/:/system/etc/voicecommand/voiceui/uipattern/Chinese-Taiwan/ \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/English/cmd_pattern:/system/etc/voicecommand/voiceui/uipattern/English/cmd_pattern \
	vendor/explay/Alto/etc/voicecommand/voiceui/uipattern/English/:/system/etc/voicecommand/voiceui/uipattern/English/ \
	vendor/explay/Alto/etc/wide-dhcpv6/dhcp6c.conf:/system/etc/wide-dhcpv6/dhcp6c.conf \
	vendor/explay/Alto/etc/wide-dhcpv6/dhcp6cctlkey:/system/etc/wide-dhcpv6/dhcp6cctlkey \
	vendor/explay/Alto/etc/wide-dhcpv6/dhcp6cDNS.conf:/system/etc/wide-dhcpv6/dhcp6cDNS.conf \
	vendor/explay/Alto/etc/wide-dhcpv6/dhcp6c.script:/system/etc/wide-dhcpv6/dhcp6c.script \
	vendor/explay/Alto/etc/wide-dhcpv6/dhcp6s.conf:/system/etc/wide-dhcpv6/dhcp6s.conf \
	vendor/explay/Alto/etc/wide-dhcpv6/:/system/etc/wide-dhcpv6/ \
	vendor/explay/Alto/etc/wifi/p2p_supplicant.conf:/system/etc/wifi/p2p_supplicant.conf \
	vendor/explay/Alto/etc/wifi/wpa_supplicant.conf:/system/etc/wifi/wpa_supplicant.conf \
	vendor/explay/Alto/etc/wifi/:/system/etc/wifi/ \
	vendor/explay/Alto/lib/crtbegin_so.o:/system/lib/crtbegin_so.o \
	vendor/explay/Alto/lib/crtend_so.o:/system/lib/crtend_so.o \
	vendor/explay/Alto/lib/drm:/system/lib/drm \
	vendor/explay/Alto/lib/egl:/system/lib/egl \
	vendor/explay/Alto/lib/hw:/system/lib/hw \
	vendor/explay/Alto/lib/liba3m.so:/system/lib/liba3m.so \
	vendor/explay/Alto/lib/libacdk.so:/system/lib/libacdk.so \
	vendor/explay/Alto/lib/libaed.so:/system/lib/libaed.so \
	vendor/explay/Alto/lib/libamrvt.so:/system/lib/libamrvt.so \
	vendor/explay/Alto/lib/libamr_wrap.so:/system/lib/libamr_wrap.so \
	vendor/explay/Alto/lib/libandroidfw.so:/system/lib/libandroidfw.so \
	vendor/explay/Alto/lib/libandroid_runtime.so:/system/lib/libandroid_runtime.so \
	vendor/explay/Alto/lib/libandroid_servers.so:/system/lib/libandroid_servers.so \
	vendor/explay/Alto/lib/libandroid.so:/system/lib/libandroid.so \
	vendor/explay/Alto/lib/libAppDataSearch.so:/system/lib/libAppDataSearch.so \
	vendor/explay/Alto/lib/libatvctrlservice.so:/system/lib/libatvctrlservice.so \
	vendor/explay/Alto/lib/libaudio.a2dp.default.so:/system/lib/libaudio.a2dp.default.so \
	vendor/explay/Alto/lib/libaudiocompensationfilter.so:/system/lib/libaudiocompensationfilter.so \
	vendor/explay/Alto/lib/libaudiocustparam.so:/system/lib/libaudiocustparam.so \
	vendor/explay/Alto/lib/libaudioeffect_jni.so:/system/lib/libaudioeffect_jni.so \
	vendor/explay/Alto/lib/libaudioflinger.so:/system/lib/libaudioflinger.so \
	vendor/explay/Alto/lib/libaudio.primary.default.so:/system/lib/libaudio.primary.default.so \
	vendor/explay/Alto/lib/libaudio-resampler.so:/system/lib/libaudio-resampler.so \
	vendor/explay/Alto/lib/libaudiosetting.so:/system/lib/libaudiosetting.so \
	vendor/explay/Alto/lib/libaudioutils.so:/system/lib/libaudioutils.so \
	vendor/explay/Alto/lib/libawb_wrap.so:/system/lib/libawb_wrap.so \
	vendor/explay/Alto/lib/libbcc.sha1.so:/system/lib/libbcc.sha1.so \
	vendor/explay/Alto/lib/libbcc.so:/system/lib/libbcc.so \
	vendor/explay/Alto/lib/libbcinfo.so:/system/lib/libbcinfo.so \
	vendor/explay/Alto/lib/libbessound_mtk.so:/system/lib/libbessound_mtk.so \
	vendor/explay/Alto/lib/libbinder.so:/system/lib/libbinder.so \
	vendor/explay/Alto/lib/libblisrc.so:/system/lib/libblisrc.so \
	vendor/explay/Alto/lib/libbluetoothdrv.so:/system/lib/libbluetoothdrv.so \
	vendor/explay/Alto/lib/libbluetoothem_mtk.so:/system/lib/libbluetoothem_mtk.so \
	vendor/explay/Alto/lib/libbluetooth_mtk.so:/system/lib/libbluetooth_mtk.so \
	vendor/explay/Alto/lib/libbluetooth_relayer.so:/system/lib/libbluetooth_relayer.so \
	vendor/explay/Alto/lib/libbtcust.so:/system/lib/libbtcust.so \
	vendor/explay/Alto/lib/libbtcusttable.so:/system/lib/libbtcusttable.so \
	vendor/explay/Alto/lib/libbtem.so:/system/lib/libbtem.so \
	vendor/explay/Alto/lib/libbtpcm.so:/system/lib/libbtpcm.so \
	vendor/explay/Alto/lib/libbtsniff.so:/system/lib/libbtsniff.so \
	vendor/explay/Alto/lib/libbwc.so:/system/lib/libbwc.so \
	vendor/explay/Alto/lib/libcache_local.so:/system/lib/libcache_local.so \
	vendor/explay/Alto/lib/libcamalgo.so:/system/lib/libcamalgo.so \
	vendor/explay/Alto/lib/libcam.camadapter.so:/system/lib/libcam.camadapter.so \
	vendor/explay/Alto/lib/libcam_camera_exif.so:/system/lib/libcam_camera_exif.so \
	vendor/explay/Alto/lib/libcam.campipe.so:/system/lib/libcam.campipe.so \
	vendor/explay/Alto/lib/libcam.camshot.so:/system/lib/libcam.camshot.so \
	vendor/explay/Alto/lib/libcam.client.so:/system/lib/libcam.client.so \
	vendor/explay/Alto/lib/libcamdrv.so:/system/lib/libcamdrv.so \
	vendor/explay/Alto/lib/libcamera_client.so:/system/lib/libcamera_client.so \
	vendor/explay/Alto/lib/libcameracustom.so:/system/lib/libcameracustom.so \
	vendor/explay/Alto/lib/libcamera_metadata.so:/system/lib/libcamera_metadata.so \
	vendor/explay/Alto/lib/libcameraservice.so:/system/lib/libcameraservice.so \
	vendor/explay/Alto/lib/libcam.paramsmgr.so:/system/lib/libcam.paramsmgr.so \
	vendor/explay/Alto/lib/libcam.utils.so:/system/lib/libcam.utils.so \
	vendor/explay/Alto/lib/libchromeview.so:/system/lib/libchromeview.so \
	vendor/explay/Alto/lib/libchromium_net.so:/system/lib/libchromium_net.so \
	vendor/explay/Alto/lib/libclcore.bc:/system/lib/libclcore.bc \
	vendor/explay/Alto/lib/libclcore_neon.bc:/system/lib/libclcore_neon.bc \
	vendor/explay/Alto/lib/libcommon_time_client.so:/system/lib/libcommon_time_client.so \
	vendor/explay/Alto/lib/libCore.so:/system/lib/libCore.so \
	vendor/explay/Alto/lib/libcorkscrew.so:/system/lib/libcorkscrew.so \
	vendor/explay/Alto/lib/libcrypto.so:/system/lib/libcrypto.so \
	vendor/explay/Alto/lib/libc.so:/system/lib/libc.so \
	vendor/explay/Alto/lib/libctest.so:/system/lib/libctest.so \
	vendor/explay/Alto/lib/libcustom_jni.so:/system/lib/libcustom_jni.so \
	vendor/explay/Alto/lib/libcustom_nvram.so:/system/lib/libcustom_nvram.so \
	vendor/explay/Alto/lib/libcutils.so:/system/lib/libcutils.so \
	vendor/explay/Alto/lib/libcvsd_mtk.so:/system/lib/libcvsd_mtk.so \
	vendor/explay/Alto/lib/libdbus.so:/system/lib/libdbus.so \
	vendor/explay/Alto/lib/libdcfdecoderjni.so:/system/lib/libdcfdecoderjni.so \
	vendor/explay/Alto/lib/libdefcontainer_jni.so:/system/lib/libdefcontainer_jni.so \
	vendor/explay/Alto/lib/libdiskconfig.so:/system/lib/libdiskconfig.so \
	vendor/explay/Alto/lib/libdl.so:/system/lib/libdl.so \
	vendor/explay/Alto/lib/libdpframework.so:/system/lib/libdpframework.so \
	vendor/explay/Alto/lib/libdrm1_jni.so:/system/lib/libdrm1_jni.so \
	vendor/explay/Alto/lib/libdrm1.so:/system/lib/libdrm1.so \
	vendor/explay/Alto/lib/libdrmframework_jni.so:/system/lib/libdrmframework_jni.so \
	vendor/explay/Alto/lib/libdrmframework.so:/system/lib/libdrmframework.so \
	vendor/explay/Alto/lib/libdrmmtkutil.so:/system/lib/libdrmmtkutil.so \
	vendor/explay/Alto/lib/libdrmmtkwhitelist.so:/system/lib/libdrmmtkwhitelist.so \
	vendor/explay/Alto/lib/libdvm.so:/system/lib/libdvm.so \
	vendor/explay/Alto/lib/libeffects.so:/system/lib/libeffects.so \
	vendor/explay/Alto/lib/libEGL.so:/system/lib/libEGL.so \
	vendor/explay/Alto/lib/libem_bt_jni.so:/system/lib/libem_bt_jni.so \
	vendor/explay/Alto/lib/libem_gpio_jni.so:/system/lib/libem_gpio_jni.so \
	vendor/explay/Alto/lib/libem_modem_jni.so:/system/lib/libem_modem_jni.so \
	vendor/explay/Alto/lib/libemoji.so:/system/lib/libemoji.so \
	vendor/explay/Alto/lib/libem_support_jni.so:/system/lib/libem_support_jni.so \
	vendor/explay/Alto/lib/libem_usb_jni.so:/system/lib/libem_usb_jni.so \
	vendor/explay/Alto/lib/libem_wifi_jni.so:/system/lib/libem_wifi_jni.so \
	vendor/explay/Alto/lib/libETC1.so:/system/lib/libETC1.so \
	vendor/explay/Alto/lib/libexif_jni.so:/system/lib/libexif_jni.so \
	vendor/explay/Alto/lib/libexif.so:/system/lib/libexif.so \
	vendor/explay/Alto/lib/libexpat.so:/system/lib/libexpat.so \
	vendor/explay/Alto/lib/libext4_utils.so:/system/lib/libext4_utils.so \
	vendor/explay/Alto/lib/libextavrcp_jni.so:/system/lib/libextavrcp_jni.so \
	vendor/explay/Alto/lib/libextavrcp.so:/system/lib/libextavrcp.so \
	vendor/explay/Alto/lib/libextbip_jni.so:/system/lib/libextbip_jni.so \
	vendor/explay/Alto/lib/libextbip.so:/system/lib/libextbip.so \
	vendor/explay/Alto/lib/libextbpp_jni.so:/system/lib/libextbpp_jni.so \
	vendor/explay/Alto/lib/libextbpp.so:/system/lib/libextbpp.so \
	vendor/explay/Alto/lib/libextdun_jni.so:/system/lib/libextdun_jni.so \
	vendor/explay/Alto/lib/libextftp_jni.so:/system/lib/libextftp_jni.so \
	vendor/explay/Alto/lib/libextftp.so:/system/lib/libextftp.so \
	vendor/explay/Alto/lib/libexthid_jni.so:/system/lib/libexthid_jni.so \
	vendor/explay/Alto/lib/libexthid.so:/system/lib/libexthid.so \
	vendor/explay/Alto/lib/libextjsr82.so:/system/lib/libextjsr82.so \
	vendor/explay/Alto/lib/libextmap_jni.so:/system/lib/libextmap_jni.so \
	vendor/explay/Alto/lib/libextmap.so:/system/lib/libextmap.so \
	vendor/explay/Alto/lib/libextopp_jni.so:/system/lib/libextopp_jni.so \
	vendor/explay/Alto/lib/libextopp.so:/system/lib/libextopp.so \
	vendor/explay/Alto/lib/libextpan_jni.so:/system/lib/libextpan_jni.so \
	vendor/explay/Alto/lib/libextpbap_jni.so:/system/lib/libextpbap_jni.so \
	vendor/explay/Alto/lib/libextpbap.so:/system/lib/libextpbap.so \
	vendor/explay/Alto/lib/libextsimap_jni.so:/system/lib/libextsimap_jni.so \
	vendor/explay/Alto/lib/libextsimap.so:/system/lib/libextsimap.so \
	vendor/explay/Alto/lib/libextsys_jni.so:/system/lib/libextsys_jni.so \
	vendor/explay/Alto/lib/libextsys.so:/system/lib/libextsys.so \
	vendor/explay/Alto/lib/libexttestmode.so:/system/lib/libexttestmode.so \
	vendor/explay/Alto/lib/libfacelock_jni.so:/system/lib/libfacelock_jni.so \
	vendor/explay/Alto/lib/libfeatureio.so:/system/lib/libfeatureio.so \
	vendor/explay/Alto/lib/libFFTEm.so:/system/lib/libFFTEm.so \
	vendor/explay/Alto/lib/libfile_op.so:/system/lib/libfile_op.so \
	vendor/explay/Alto/lib/libfilterfw.so:/system/lib/libfilterfw.so \
	vendor/explay/Alto/lib/libfilterpack_facedetect.so:/system/lib/libfilterpack_facedetect.so \
	vendor/explay/Alto/lib/libfilterpack_imageproc.so:/system/lib/libfilterpack_imageproc.so \
	vendor/explay/Alto/lib/libflvextractor.so:/system/lib/libflvextractor.so \
	vendor/explay/Alto/lib/libflv.so:/system/lib/libflv.so \
	vendor/explay/Alto/lib/libfmcust.so:/system/lib/libfmcust.so \
	vendor/explay/Alto/lib/libfmjni.so:/system/lib/libfmjni.so \
	vendor/explay/Alto/lib/libfmmt6620.so:/system/lib/libfmmt6620.so \
	vendor/explay/Alto/lib/libfmmt6627.so:/system/lib/libfmmt6627.so \
	vendor/explay/Alto/lib/libfmmt6628.so:/system/lib/libfmmt6628.so \
	vendor/explay/Alto/lib/libfrsdk.so:/system/lib/libfrsdk.so \
	vendor/explay/Alto/lib/libft.so:/system/lib/libft.so \
	vendor/explay/Alto/lib/libgabi++.so:/system/lib/libgabi++.so \
	vendor/explay/Alto/lib/libgames_rtmp_jni.so:/system/lib/libgames_rtmp_jni.so \
	vendor/explay/Alto/lib/libgccdemangle.so:/system/lib/libgccdemangle.so \
	vendor/explay/Alto/lib/libgcomm_jni.so:/system/lib/libgcomm_jni.so \
	vendor/explay/Alto/lib/libGdmaScalerPipe.so:/system/lib/libGdmaScalerPipe.so \
	vendor/explay/Alto/lib/libGLES_trace.so:/system/lib/libGLES_trace.so \
	vendor/explay/Alto/lib/libGLESv1_CM.so:/system/lib/libGLESv1_CM.so \
	vendor/explay/Alto/lib/libGLESv2.so:/system/lib/libGLESv2.so \
	vendor/explay/Alto/lib/libgnustl_shared.so:/system/lib/libgnustl_shared.so \
	vendor/explay/Alto/lib/libgoggles_clientvision.so:/system/lib/libgoggles_clientvision.so \
	vendor/explay/Alto/lib/libgoogle_recognizer_jni_l.so:/system/lib/libgoogle_recognizer_jni_l.so \
	vendor/explay/Alto/lib/libgoogle_recognizer_jni.so:/system/lib/libgoogle_recognizer_jni.so \
	vendor/explay/Alto/lib/libgraphite2.so:/system/lib/libgraphite2.so \
	vendor/explay/Alto/lib/libgtalk_jni.so:/system/lib/libgtalk_jni.so \
	vendor/explay/Alto/lib/libgtalk_stabilize.so:/system/lib/libgtalk_stabilize.so \
	vendor/explay/Alto/lib/libgui.so:/system/lib/libgui.so \
	vendor/explay/Alto/lib/libh264dec_customize.so:/system/lib/libh264dec_customize.so \
	vendor/explay/Alto/lib/libh264dec_xa.ca7.so:/system/lib/libh264dec_xa.ca7.so \
	vendor/explay/Alto/lib/libh264dec_xb.ca7.so:/system/lib/libh264dec_xb.ca7.so \
	vendor/explay/Alto/lib/libh264enc_sa.ca7.so:/system/lib/libh264enc_sa.ca7.so \
	vendor/explay/Alto/lib/libh264enc_sb.ca7.so:/system/lib/libh264enc_sb.ca7.so \
	vendor/explay/Alto/lib/libhardware_legacy.so:/system/lib/libhardware_legacy.so \
	vendor/explay/Alto/lib/libhardware.so:/system/lib/libhardware.so \
	vendor/explay/Alto/lib/libharfbuzz_ng.so:/system/lib/libharfbuzz_ng.so \
	vendor/explay/Alto/lib/libharfbuzz.so:/system/lib/libharfbuzz.so \
	vendor/explay/Alto/lib/libhwm.so:/system/lib/libhwm.so \
	vendor/explay/Alto/lib/libhwui.so:/system/lib/libhwui.so \
	vendor/explay/Alto/lib/libI420colorconvert.so:/system/lib/libI420colorconvert.so \
	vendor/explay/Alto/lib/libicui18n.so:/system/lib/libicui18n.so \
	vendor/explay/Alto/lib/libicuuc.so:/system/lib/libicuuc.so \
	vendor/explay/Alto/lib/libimageio.so:/system/lib/libimageio.so \
	vendor/explay/Alto/lib/libinput.so:/system/lib/libinput.so \
	vendor/explay/Alto/lib/libion.so:/system/lib/libion.so \
	vendor/explay/Alto/lib/libipod.so:/system/lib/libipod.so \
	vendor/explay/Alto/lib/libiprouteutil.so:/system/lib/libiprouteutil.so \
	vendor/explay/Alto/lib/libja3m.so:/system/lib/libja3m.so \
	vendor/explay/Alto/lib/libjavacore.so:/system/lib/libjavacore.so \
	vendor/explay/Alto/lib/libJniAtvService.so:/system/lib/libJniAtvService.so \
	vendor/explay/Alto/lib/libjni_eglfence.so:/system/lib/libjni_eglfence.so \
	vendor/explay/Alto/lib/libjni_filtershow_filters.so:/system/lib/libjni_filtershow_filters.so \
	vendor/explay/Alto/lib/libjnigraphics.so:/system/lib/libjnigraphics.so \
	vendor/explay/Alto/lib/libjni_latinime.so:/system/lib/libjni_latinime.so \
	vendor/explay/Alto/lib/libjni_pq.so:/system/lib/libjni_pq.so \
	vendor/explay/Alto/lib/libjpeg.so:/system/lib/libjpeg.so \
	vendor/explay/Alto/lib/libJpgDecPipe.so:/system/lib/libJpgDecPipe.so \
	vendor/explay/Alto/lib/libJpgEncPipe.so:/system/lib/libJpgEncPipe.so \
	vendor/explay/Alto/lib/libkeystore_client.so:/system/lib/libkeystore_client.so \
	vendor/explay/Alto/lib/libLibs.so:/system/lib/libLibs.so \
	vendor/explay/Alto/lib/liblog.so:/system/lib/liblog.so \
	vendor/explay/Alto/lib/libm4u.so:/system/lib/libm4u.so \
	vendor/explay/Alto/lib/libMali.so:/system/lib/libMali.so \
	vendor/explay/Alto/lib/libmatv_cust.so:/system/lib/libmatv_cust.so \
	vendor/explay/Alto/lib/libmdnssd.so:/system/lib/libmdnssd.so \
	vendor/explay/Alto/lib/libmedia_jni.so:/system/lib/libmedia_jni.so \
	vendor/explay/Alto/lib/libmedia_native.so:/system/lib/libmedia_native.so \
	vendor/explay/Alto/lib/libmediaplayerservice.so:/system/lib/libmediaplayerservice.so \
	vendor/explay/Alto/lib/libmedia.so:/system/lib/libmedia.so \
	vendor/explay/Alto/lib/libmediatek_exceptionlog.so:/system/lib/libmediatek_exceptionlog.so \
	vendor/explay/Alto/lib/libmemorydumper.so:/system/lib/libmemorydumper.so \
	vendor/explay/Alto/lib/libmhalImageCodec.so:/system/lib/libmhalImageCodec.so \
	vendor/explay/Alto/lib/libmmprofile_jni.so:/system/lib/libmmprofile_jni.so \
	vendor/explay/Alto/lib/libmmprofile.so:/system/lib/libmmprofile.so \
	vendor/explay/Alto/lib/libmp4dec_customize.so:/system/lib/libmp4dec_customize.so \
	vendor/explay/Alto/lib/libmp4dec_sa.ca7.so:/system/lib/libmp4dec_sa.ca7.so \
	vendor/explay/Alto/lib/libmp4dec_sb.ca7.so:/system/lib/libmp4dec_sb.ca7.so \
	vendor/explay/Alto/lib/libmp4enc_xa.ca7.so:/system/lib/libmp4enc_xa.ca7.so \
	vendor/explay/Alto/lib/libmp4enc_xb.ca7.so:/system/lib/libmp4enc_xb.ca7.so \
	vendor/explay/Alto/lib/libmpodecoder.so:/system/lib/libmpodecoder.so \
	vendor/explay/Alto/lib/libmpoencoder.so:/system/lib/libmpoencoder.so \
	vendor/explay/Alto/lib/libmpojni.so:/system/lib/libmpojni.so \
	vendor/explay/Alto/lib/libmpo.so:/system/lib/libmpo.so \
	vendor/explay/Alto/lib/libm.so:/system/lib/libm.so \
	vendor/explay/Alto/lib/libmtka2dp.so:/system/lib/libmtka2dp.so \
	vendor/explay/Alto/lib/libmtkbtextadpa2dp.so:/system/lib/libmtkbtextadpa2dp.so \
	vendor/explay/Alto/lib/libmtkbtextadp.so:/system/lib/libmtkbtextadp.so \
	vendor/explay/Alto/lib/libmtkbtextpan.so:/system/lib/libmtkbtextpan.so \
	vendor/explay/Alto/lib/libmtkbtextspp.so:/system/lib/libmtkbtextspp.so \
	vendor/explay/Alto/lib/libmtk_drvb.so:/system/lib/libmtk_drvb.so \
	vendor/explay/Alto/lib/libmtkhdmi_jni.so:/system/lib/libmtkhdmi_jni.so \
	vendor/explay/Alto/lib/libMtkOmxAacDec.so:/system/lib/libMtkOmxAacDec.so \
	vendor/explay/Alto/lib/libMtkOmxAacEnc.so:/system/lib/libMtkOmxAacEnc.so \
	vendor/explay/Alto/lib/libMtkOmxAdpcmDec.so:/system/lib/libMtkOmxAdpcmDec.so \
	vendor/explay/Alto/lib/libMtkOmxAdpcmEnc.so:/system/lib/libMtkOmxAdpcmEnc.so \
	vendor/explay/Alto/lib/libMtkOmxAmrEnc.so:/system/lib/libMtkOmxAmrEnc.so \
	vendor/explay/Alto/lib/libMtkOmxAMRNBDec.so:/system/lib/libMtkOmxAMRNBDec.so \
	vendor/explay/Alto/lib/libMtkOmxAMRWBDec.so:/system/lib/libMtkOmxAMRWBDec.so \
	vendor/explay/Alto/lib/libMtkOmxApeDec.so:/system/lib/libMtkOmxApeDec.so \
	vendor/explay/Alto/lib/libMtkOmxAwbEnc.so:/system/lib/libMtkOmxAwbEnc.so \
	vendor/explay/Alto/lib/libMtkOmxCore.so:/system/lib/libMtkOmxCore.so \
	vendor/explay/Alto/lib/libMtkOmxFlacDec.so:/system/lib/libMtkOmxFlacDec.so \
	vendor/explay/Alto/lib/libMtkOmxG711Dec.so:/system/lib/libMtkOmxG711Dec.so \
	vendor/explay/Alto/lib/libMtkOmxMp3Dec.so:/system/lib/libMtkOmxMp3Dec.so \
	vendor/explay/Alto/lib/libMtkOmxRawDec.so:/system/lib/libMtkOmxRawDec.so \
	vendor/explay/Alto/lib/libMtkOmxVdec.so:/system/lib/libMtkOmxVdec.so \
	vendor/explay/Alto/lib/libMtkOmxVenc.so:/system/lib/libMtkOmxVenc.so \
	vendor/explay/Alto/lib/libMtkOmxVorbisDec.so:/system/lib/libMtkOmxVorbisDec.so \
	vendor/explay/Alto/lib/libMtkOmxVorbisEnc.so:/system/lib/libMtkOmxVorbisEnc.so \
	vendor/explay/Alto/lib/libmtkplayer.so:/system/lib/libmtkplayer.so \
	vendor/explay/Alto/lib/libMtkVideoTranscoder.so:/system/lib/libMtkVideoTranscoder.so \
	vendor/explay/Alto/lib/libmtk_vt_client.so:/system/lib/libmtk_vt_client.so \
	vendor/explay/Alto/lib/libmtk_vt_em.so:/system/lib/libmtk_vt_em.so \
	vendor/explay/Alto/lib/libmtk_vt_service.so:/system/lib/libmtk_vt_service.so \
	vendor/explay/Alto/lib/libmtk_vt_swip.so:/system/lib/libmtk_vt_swip.so \
	vendor/explay/Alto/lib/libmtk_vt_utils.so:/system/lib/libmtk_vt_utils.so \
	vendor/explay/Alto/lib/libmtp.so:/system/lib/libmtp.so \
	vendor/explay/Alto/lib/libnativecheck-jni.so:/system/lib/libnativecheck-jni.so \
	vendor/explay/Alto/lib/libnativehelper.so:/system/lib/libnativehelper.so \
	vendor/explay/Alto/lib/libnbaio.so:/system/lib/libnbaio.so \
	vendor/explay/Alto/lib/libnetlink.so:/system/lib/libnetlink.so \
	vendor/explay/Alto/lib/libnetutils.so:/system/lib/libnetutils.so \
	vendor/explay/Alto/lib/libnvram_daemon_callback.so:/system/lib/libnvram_daemon_callback.so \
	vendor/explay/Alto/lib/libnvram.so:/system/lib/libnvram.so \
	vendor/explay/Alto/lib/libOpenMAXAL.so:/system/lib/libOpenMAXAL.so \
	vendor/explay/Alto/lib/libOpenSLES.so:/system/lib/libOpenSLES.so \
	vendor/explay/Alto/lib/libpalsecurity.so:/system/lib/libpalsecurity.so \
	vendor/explay/Alto/lib/libPAL.so:/system/lib/libPAL.so \
	vendor/explay/Alto/lib/libpalwlan_mtk.so:/system/lib/libpalwlan_mtk.so \
	vendor/explay/Alto/lib/libpatts_engine_jni_api.so:/system/lib/libpatts_engine_jni_api.so \
	vendor/explay/Alto/lib/libperfservice.so:/system/lib/libperfservice.so \
	vendor/explay/Alto/lib/libpixelflinger.so:/system/lib/libpixelflinger.so \
	vendor/explay/Alto/lib/libplus_jni_v8.so:/system/lib/libplus_jni_v8.so \
	vendor/explay/Alto/lib/libportable.so:/system/lib/libportable.so \
	vendor/explay/Alto/lib/libpowermanager.so:/system/lib/libpowermanager.so \
	vendor/explay/Alto/lib/libpower.so:/system/lib/libpower.so \
	vendor/explay/Alto/lib/libpppbtdun.so:/system/lib/libpppbtdun.so \
	vendor/explay/Alto/lib/libreference-ril.so:/system/lib/libreference-ril.so \
	vendor/explay/Alto/lib/librilmtkmd2.so:/system/lib/librilmtkmd2.so \
	vendor/explay/Alto/lib/librilmtk.so:/system/lib/librilmtk.so \
	vendor/explay/Alto/lib/libril.so:/system/lib/libril.so \
	vendor/explay/Alto/lib/librs.antblur_constant.so:/system/lib/librs.antblur_constant.so \
	vendor/explay/Alto/lib/librs.antblur_drama.so:/system/lib/librs.antblur_drama.so \
	vendor/explay/Alto/lib/librs.antblur.so:/system/lib/librs.antblur.so \
	vendor/explay/Alto/lib/librs.drama.so:/system/lib/librs.drama.so \
	vendor/explay/Alto/lib/libRSDriver.so:/system/lib/libRSDriver.so \
	vendor/explay/Alto/lib/librs.film_base.so:/system/lib/librs.film_base.so \
	vendor/explay/Alto/lib/librs.fixedframe.so:/system/lib/librs.fixedframe.so \
	vendor/explay/Alto/lib/librs.grey.so:/system/lib/librs.grey.so \
	vendor/explay/Alto/lib/librs.image_wrapper.so:/system/lib/librs.image_wrapper.so \
	vendor/explay/Alto/lib/librs_jni.so:/system/lib/librs_jni.so \
	vendor/explay/Alto/lib/librsjni.so:/system/lib/librsjni.so \
	vendor/explay/Alto/lib/librs.retrolux.so:/system/lib/librs.retrolux.so \
	vendor/explay/Alto/lib/libRS.so:/system/lib/libRS.so \
	vendor/explay/Alto/lib/libRSSupport.so:/system/lib/libRSSupport.so \
	vendor/explay/Alto/lib/librtp_jni.so:/system/lib/librtp_jni.so \
	vendor/explay/Alto/lib/libsched.so:/system/lib/libsched.so \
	vendor/explay/Alto/lib/libsec.so:/system/lib/libsec.so \
	vendor/explay/Alto/lib/libsensorservice.so:/system/lib/libsensorservice.so \
	vendor/explay/Alto/lib/libskia.so:/system/lib/libskia.so \
	vendor/explay/Alto/lib/libsonivox.so:/system/lib/libsonivox.so \
	vendor/explay/Alto/lib/libsoundpool.so:/system/lib/libsoundpool.so \
	vendor/explay/Alto/lib/libsparse.so:/system/lib/libsparse.so \
	vendor/explay/Alto/lib/libspeech_enh_lib.so:/system/lib/libspeech_enh_lib.so \
	vendor/explay/Alto/lib/libSpeechKitGUI.so:/system/lib/libSpeechKitGUI.so \
	vendor/explay/Alto/lib/libSpeechKit.so:/system/lib/libSpeechKit.so \
	vendor/explay/Alto/lib/libspeexresampler.so:/system/lib/libspeexresampler.so \
	vendor/explay/Alto/lib/libspeexwrapper.so:/system/lib/libspeexwrapper.so \
	vendor/explay/Alto/lib/libsqlite_jni.so:/system/lib/libsqlite_jni.so \
	vendor/explay/Alto/lib/libsqlite.so:/system/lib/libsqlite.so \
	vendor/explay/Alto/lib/libSR_AudioIn.so:/system/lib/libSR_AudioIn.so \
	vendor/explay/Alto/lib/libssladp.so:/system/lib/libssladp.so \
	vendor/explay/Alto/lib/libssl.so:/system/lib/libssl.so \
	vendor/explay/Alto/lib/libstagefright_amrnb_common.so:/system/lib/libstagefright_amrnb_common.so \
	vendor/explay/Alto/lib/libstagefright_avc_common.so:/system/lib/libstagefright_avc_common.so \
	vendor/explay/Alto/lib/libstagefright_chromium_http.so:/system/lib/libstagefright_chromium_http.so \
	vendor/explay/Alto/lib/libstagefright_enc_common.so:/system/lib/libstagefright_enc_common.so \
	vendor/explay/Alto/lib/libstagefright_foundation.so:/system/lib/libstagefright_foundation.so \
	vendor/explay/Alto/lib/libstagefrighthw.so:/system/lib/libstagefrighthw.so \
	vendor/explay/Alto/lib/libstagefright_memutil.so:/system/lib/libstagefright_memutil.so \
	vendor/explay/Alto/lib/libstagefright_omx.so:/system/lib/libstagefright_omx.so \
	vendor/explay/Alto/lib/libstagefright.so:/system/lib/libstagefright.so \
	vendor/explay/Alto/lib/libstagefright_soft_aacdec.so:/system/lib/libstagefright_soft_aacdec.so \
	vendor/explay/Alto/lib/libstagefright_soft_aacenc.so:/system/lib/libstagefright_soft_aacenc.so \
	vendor/explay/Alto/lib/libstagefright_soft_amrdec.so:/system/lib/libstagefright_soft_amrdec.so \
	vendor/explay/Alto/lib/libstagefright_soft_amrnbenc.so:/system/lib/libstagefright_soft_amrnbenc.so \
	vendor/explay/Alto/lib/libstagefright_soft_amrwbenc.so:/system/lib/libstagefright_soft_amrwbenc.so \
	vendor/explay/Alto/lib/libstagefright_soft_flacenc.so:/system/lib/libstagefright_soft_flacenc.so \
	vendor/explay/Alto/lib/libstagefright_soft_g711dec.so:/system/lib/libstagefright_soft_g711dec.so \
	vendor/explay/Alto/lib/libstagefright_soft_h264dec.so:/system/lib/libstagefright_soft_h264dec.so \
	vendor/explay/Alto/lib/libstagefright_soft_h264enc.so:/system/lib/libstagefright_soft_h264enc.so \
	vendor/explay/Alto/lib/libstagefright_soft_mp3dec.so:/system/lib/libstagefright_soft_mp3dec.so \
	vendor/explay/Alto/lib/libstagefright_soft_mpeg4dec.so:/system/lib/libstagefright_soft_mpeg4dec.so \
	vendor/explay/Alto/lib/libstagefright_soft_mpeg4enc.so:/system/lib/libstagefright_soft_mpeg4enc.so \
	vendor/explay/Alto/lib/libstagefright_soft_rawdec.so:/system/lib/libstagefright_soft_rawdec.so \
	vendor/explay/Alto/lib/libstagefright_soft_vorbisdec.so:/system/lib/libstagefright_soft_vorbisdec.so \
	vendor/explay/Alto/lib/libstagefright_soft_vpxdec.so:/system/lib/libstagefright_soft_vpxdec.so \
	vendor/explay/Alto/lib/libstagefright_wfd.so:/system/lib/libstagefright_wfd.so \
	vendor/explay/Alto/lib/libstagefright_yuv.so:/system/lib/libstagefright_yuv.so \
	vendor/explay/Alto/lib/libstdc++.so:/system/lib/libstdc++.so \
	vendor/explay/Alto/lib/libstlport.so:/system/lib/libstlport.so \
	vendor/explay/Alto/lib/libsurfaceflinger_ddmconnection.so:/system/lib/libsurfaceflinger_ddmconnection.so \
	vendor/explay/Alto/lib/libsurfaceflinger.so:/system/lib/libsurfaceflinger.so \
	vendor/explay/Alto/lib/libsuspend.so:/system/lib/libsuspend.so \
	vendor/explay/Alto/lib/libSwJpgCodec.so:/system/lib/libSwJpgCodec.so \
	vendor/explay/Alto/lib/libsync.so:/system/lib/libsync.so \
	vendor/explay/Alto/lib/libsystem_server.so:/system/lib/libsystem_server.so \
	vendor/explay/Alto/lib/libsysutils.so:/system/lib/libsysutils.so \
	vendor/explay/Alto/lib/libthread_db.so:/system/lib/libthread_db.so \
	vendor/explay/Alto/lib/libtinyalsa.so:/system/lib/libtinyalsa.so \
	vendor/explay/Alto/lib/libtinyxml.so:/system/lib/libtinyxml.so \
	vendor/explay/Alto/lib/libttscompat.so:/system/lib/libttscompat.so \
	vendor/explay/Alto/lib/libttspico.so:/system/lib/libttspico.so \
	vendor/explay/Alto/lib/libtvoutjni.so:/system/lib/libtvoutjni.so \
	vendor/explay/Alto/lib/libtvoutpattern.so:/system/lib/libtvoutpattern.so \
	vendor/explay/Alto/lib/libui.so:/system/lib/libui.so \
	vendor/explay/Alto/lib/libusbhost.so:/system/lib/libusbhost.so \
	vendor/explay/Alto/lib/libutilrilmtk.so:/system/lib/libutilrilmtk.so \
	vendor/explay/Alto/lib/libutils.so:/system/lib/libutils.so \
	vendor/explay/Alto/lib/libvariablespeed.so:/system/lib/libvariablespeed.so \
	vendor/explay/Alto/lib/libvcdecoder_jni.so:/system/lib/libvcdecoder_jni.so \
	vendor/explay/Alto/lib/libvcodecdrv.so:/system/lib/libvcodecdrv.so \
	vendor/explay/Alto/lib/libvcodec_oal.so:/system/lib/libvcodec_oal.so \
	vendor/explay/Alto/lib/libvcodec_utility.so:/system/lib/libvcodec_utility.so \
	vendor/explay/Alto/lib/libvideochat_jni.so:/system/lib/libvideochat_jni.so \
	vendor/explay/Alto/lib/libvoicerecognition_jni.so:/system/lib/libvoicerecognition_jni.so \
	vendor/explay/Alto/lib/libvoicerecognition.so:/system/lib/libvoicerecognition.so \
	vendor/explay/Alto/lib/libvorbisencoder.so:/system/lib/libvorbisencoder.so \
	vendor/explay/Alto/lib/libvorbisidec.so:/system/lib/libvorbisidec.so \
	vendor/explay/Alto/lib/libvp8dec_xa.ca7.so:/system/lib/libvp8dec_xa.ca7.so \
	vendor/explay/Alto/lib/libvt_custom.so:/system/lib/libvt_custom.so \
	vendor/explay/Alto/lib/libvtmal.so:/system/lib/libvtmal.so \
	vendor/explay/Alto/lib/libwapi.so:/system/lib/libwapi.so \
	vendor/explay/Alto/lib/libwebcore.so:/system/lib/libwebcore.so \
	vendor/explay/Alto/lib/libwebp_android.so:/system/lib/libwebp_android.so \
	vendor/explay/Alto/lib/libwebrtc_audio_preprocessing.so:/system/lib/libwebrtc_audio_preprocessing.so \
	vendor/explay/Alto/lib/libwilhelm.so:/system/lib/libwilhelm.so \
	vendor/explay/Alto/lib/libwpa_client.so:/system/lib/libwpa_client.so \
	vendor/explay/Alto/lib/libz.so:/system/lib/libz.so \
	vendor/explay/Alto/lib/modules:/system/lib/modules \
	vendor/explay/Alto/lib/mtk-rilmd2.so:/system/lib/mtk-rilmd2.so \
	vendor/explay/Alto/lib/mtk-ril.so:/system/lib/mtk-ril.so \
	vendor/explay/Alto/lib/soundfx:/system/lib/soundfx \
	vendor/explay/Alto/lib/ssl:/system/lib/ssl \
	vendor/explay/Alto/lib/:/system/lib/ \
	vendor/explay/Alto/lib/drm/libdrmmtkplugin.so:/system/lib/drm/libdrmmtkplugin.so \
	vendor/explay/Alto/lib/drm/:/system/lib/drm/ \
	vendor/explay/Alto/lib/egl/libEGL_mali.so:/system/lib/egl/libEGL_mali.so \
	vendor/explay/Alto/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
	vendor/explay/Alto/lib/egl/libGLESv1_CM_mali.so:/system/lib/egl/libGLESv1_CM_mali.so \
	vendor/explay/Alto/lib/egl/libGLESv2_mali.so:/system/lib/egl/libGLESv2_mali.so \
	vendor/explay/Alto/lib/egl/:/system/lib/egl/ \
	vendor/explay/Alto/lib/hw/audio_policy.default.so:/system/lib/hw/audio_policy.default.so \
	vendor/explay/Alto/lib/hw/audio_policy.stub.so:/system/lib/hw/audio_policy.stub.so \
	vendor/explay/Alto/lib/hw/audio.primary.default.so:/system/lib/hw/audio.primary.default.so \
	vendor/explay/Alto/lib/hw/camera.default.so:/system/lib/hw/camera.default.so \
	vendor/explay/Alto/lib/hw/gps.default.so:/system/lib/hw/gps.default.so \
	vendor/explay/Alto/lib/hw/gralloc.default.so:/system/lib/hw/gralloc.default.so \
	vendor/explay/Alto/lib/hw/gralloc.mt6572.so:/system/lib/hw/gralloc.mt6572.so \
	vendor/explay/Alto/lib/hw/hwcomposer.mt6572.so:/system/lib/hw/hwcomposer.mt6572.so \
	vendor/explay/Alto/lib/hw/keystore.default.so:/system/lib/hw/keystore.default.so \
	vendor/explay/Alto/lib/hw/libaudio.r_submix.default.so:/system/lib/hw/libaudio.r_submix.default.so \
	vendor/explay/Alto/lib/hw/libaudio.usb.default.so:/system/lib/hw/libaudio.usb.default.so \
	vendor/explay/Alto/lib/hw/lights.default.so:/system/lib/hw/lights.default.so \
	vendor/explay/Alto/lib/hw/local_time.default.so:/system/lib/hw/local_time.default.so \
	vendor/explay/Alto/lib/hw/power.default.so:/system/lib/hw/power.default.so \
	vendor/explay/Alto/lib/hw/sensors.default.so:/system/lib/hw/sensors.default.so \
	vendor/explay/Alto/lib/hw/:/system/lib/hw/ \
	vendor/explay/Alto/lib/modules/ccci.ko:/system/lib/modules/ccci.ko \
	vendor/explay/Alto/lib/modules/ccci_plat.ko:/system/lib/modules/ccci_plat.ko \
	vendor/explay/Alto/lib/modules/devapc.ko:/system/lib/modules/devapc.ko \
	vendor/explay/Alto/lib/modules/devinfo.ko:/system/lib/modules/devinfo.ko \
	vendor/explay/Alto/lib/modules/hid-logitech-dj.ko:/system/lib/modules/hid-logitech-dj.ko \
	vendor/explay/Alto/lib/modules/mtk_fm_drv.ko:/system/lib/modules/mtk_fm_drv.ko \
	vendor/explay/Alto/lib/modules/mtk_stp_bt.ko:/system/lib/modules/mtk_stp_bt.ko \
	vendor/explay/Alto/lib/modules/mtk_stp_gps.ko:/system/lib/modules/mtk_stp_gps.ko \
	vendor/explay/Alto/lib/modules/mtk_stp_wmt.ko:/system/lib/modules/mtk_stp_wmt.ko \
	vendor/explay/Alto/lib/modules/mtk_wmt_wifi.ko:/system/lib/modules/mtk_wmt_wifi.ko \
	vendor/explay/Alto/lib/modules/scsi_tgt.ko:/system/lib/modules/scsi_tgt.ko \
	vendor/explay/Alto/lib/modules/scsi_wait_scan.ko:/system/lib/modules/scsi_wait_scan.ko \
	vendor/explay/Alto/lib/modules/sec.ko:/system/lib/modules/sec.ko \
	vendor/explay/Alto/lib/modules/vcodec_kernel_driver.ko:/system/lib/modules/vcodec_kernel_driver.ko \
	vendor/explay/Alto/lib/modules/wlan.ko:/system/lib/modules/wlan.ko \
	vendor/explay/Alto/lib/modules/wlan_mt6582.ko:/system/lib/modules/wlan_mt6582.ko \
	vendor/explay/Alto/lib/modules/:/system/lib/modules/ \
	vendor/explay/Alto/lib/soundfx/libaudiopreprocessing.so:/system/lib/soundfx/libaudiopreprocessing.so \
	vendor/explay/Alto/lib/soundfx/libbundlewrapper.so:/system/lib/soundfx/libbundlewrapper.so \
	vendor/explay/Alto/lib/soundfx/libdownmix.so:/system/lib/soundfx/libdownmix.so \
	vendor/explay/Alto/lib/soundfx/libreverbwrapper.so:/system/lib/soundfx/libreverbwrapper.so \
	vendor/explay/Alto/lib/soundfx/libvisualizer.so:/system/lib/soundfx/libvisualizer.so \
	vendor/explay/Alto/lib/soundfx/:/system/lib/soundfx/ \
	vendor/explay/Alto/lib/ssl/engines:/system/lib/ssl/engines \
	vendor/explay/Alto/lib/ssl/:/system/lib/ssl/ \
	vendor/explay/Alto/lib/ssl/engines/libkeystore.so:/system/lib/ssl/engines/libkeystore.so \
	vendor/explay/Alto/lib/ssl/engines/:/system/lib/ssl/engines/ \
	vendor/explay/Alto/usr/icu:/system/usr/icu \
	vendor/explay/Alto/usr/idc:/system/usr/idc \
	vendor/explay/Alto/usr/keychars:/system/usr/keychars \
	vendor/explay/Alto/usr/keylayout:/system/usr/keylayout \
	vendor/explay/Alto/usr/share:/system/usr/share \
	vendor/explay/Alto/usr/srec:/system/usr/srec \
	vendor/explay/Alto/usr/:/system/usr/ \
	vendor/explay/Alto/usr/icu/icudt48l.dat:/system/usr/icu/icudt48l.dat \
	vendor/explay/Alto/usr/icu/:/system/usr/icu/ \
	vendor/explay/Alto/usr/idc/hid-keyboard.idc:/system/usr/idc/hid-keyboard.idc \
	vendor/explay/Alto/usr/idc/qwerty2.idc:/system/usr/idc/qwerty2.idc \
	vendor/explay/Alto/usr/idc/qwerty.idc:/system/usr/idc/qwerty.idc \
	vendor/explay/Alto/usr/idc/:/system/usr/idc/ \
	vendor/explay/Alto/usr/keychars/Generic.kcm:/system/usr/keychars/Generic.kcm \
	vendor/explay/Alto/usr/keychars/hid-keyboard.kcm:/system/usr/keychars/hid-keyboard.kcm \
	vendor/explay/Alto/usr/keychars/qwerty2.kcm:/system/usr/keychars/qwerty2.kcm \
	vendor/explay/Alto/usr/keychars/qwerty.kcm:/system/usr/keychars/qwerty.kcm \
	vendor/explay/Alto/usr/keychars/Virtual.kcm:/system/usr/keychars/Virtual.kcm \
	vendor/explay/Alto/usr/keychars/:/system/usr/keychars/ \
	vendor/explay/Alto/usr/keylayout/ACCDET.kl:/system/usr/keylayout/ACCDET.kl \
	vendor/explay/Alto/usr/keylayout/AVRCP.kl:/system/usr/keylayout/AVRCP.kl \
	vendor/explay/Alto/usr/keylayout/Generic.kl:/system/usr/keylayout/Generic.kl \
	vendor/explay/Alto/usr/keylayout/hid-keyboard.kl:/system/usr/keylayout/hid-keyboard.kl \
	vendor/explay/Alto/usr/keylayout/mtk-kpd.kl:/system/usr/keylayout/mtk-kpd.kl \
	vendor/explay/Alto/usr/keylayout/qwerty.kl:/system/usr/keylayout/qwerty.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_045e_Product_028e.kl:/system/usr/keylayout/Vendor_045e_Product_028e.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_046d_Product_c216.kl:/system/usr/keylayout/Vendor_046d_Product_c216.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_046d_Product_c294.kl:/system/usr/keylayout/Vendor_046d_Product_c294.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_046d_Product_c299.kl:/system/usr/keylayout/Vendor_046d_Product_c299.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_046d_Product_c532.kl:/system/usr/keylayout/Vendor_046d_Product_c532.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_054c_Product_0268.kl:/system/usr/keylayout/Vendor_054c_Product_0268.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_05ac_Product_0239.kl:/system/usr/keylayout/Vendor_05ac_Product_0239.kl \
	vendor/explay/Alto/usr/keylayout/Vendor_22b8_Product_093d.kl:/system/usr/keylayout/Vendor_22b8_Product_093d.kl \
	vendor/explay/Alto/usr/keylayout/:/system/usr/keylayout/ \
	vendor/explay/Alto/usr/share/bmd:/system/usr/share/bmd \
	vendor/explay/Alto/usr/share/zoneinfo:/system/usr/share/zoneinfo \
	vendor/explay/Alto/usr/share/:/system/usr/share/ \
	vendor/explay/Alto/usr/share/bmd/RFFspeed_501.bmd:/system/usr/share/bmd/RFFspeed_501.bmd \
	vendor/explay/Alto/usr/share/bmd/RFFstd_501.bmd:/system/usr/share/bmd/RFFstd_501.bmd \
	vendor/explay/Alto/usr/share/bmd/:/system/usr/share/bmd/ \
	vendor/explay/Alto/usr/share/zoneinfo/zoneinfo.dat:/system/usr/share/zoneinfo/zoneinfo.dat \
	vendor/explay/Alto/usr/share/zoneinfo/zoneinfo.idx:/system/usr/share/zoneinfo/zoneinfo.idx \
	vendor/explay/Alto/usr/share/zoneinfo/zoneinfo.version:/system/usr/share/zoneinfo/zoneinfo.version \
	vendor/explay/Alto/usr/share/zoneinfo/:/system/usr/share/zoneinfo/ \
	vendor/explay/Alto/usr/srec/en-US:/system/usr/srec/en-US \
	vendor/explay/Alto/usr/srec/:/system/usr/srec/ \
	vendor/explay/Alto/usr/srec/en-US/acoustic_model:/system/usr/srec/en-US/acoustic_model \
	vendor/explay/Alto/usr/srec/en-US/c_fst:/system/usr/srec/en-US/c_fst \
	vendor/explay/Alto/usr/srec/en-US/clg:/system/usr/srec/en-US/clg \
	vendor/explay/Alto/usr/srec/en-US/compile_grammar.config:/system/usr/srec/en-US/compile_grammar.config \
	vendor/explay/Alto/usr/srec/en-US/contacts.abnf:/system/usr/srec/en-US/contacts.abnf \
	vendor/explay/Alto/usr/srec/en-US/dict:/system/usr/srec/en-US/dict \
	vendor/explay/Alto/usr/srec/en-US/dictation.config:/system/usr/srec/en-US/dictation.config \
	vendor/explay/Alto/usr/srec/en-US/embed_phone_nn_model:/system/usr/srec/en-US/embed_phone_nn_model \
	vendor/explay/Alto/usr/srec/en-US/embed_phone_nn_state_sym:/system/usr/srec/en-US/embed_phone_nn_state_sym \
	vendor/explay/Alto/usr/srec/en-US/endpointer_dictation.config:/system/usr/srec/en-US/endpointer_dictation.config \
	vendor/explay/Alto/usr/srec/en-US/endpointer_voicesearch.config:/system/usr/srec/en-US/endpointer_voicesearch.config \
	vendor/explay/Alto/usr/srec/en-US/ep_acoustic_model:/system/usr/srec/en-US/ep_acoustic_model \
	vendor/explay/Alto/usr/srec/en-US/g2p_fst:/system/usr/srec/en-US/g2p_fst \
	vendor/explay/Alto/usr/srec/en-US/google_hotword_clg:/system/usr/srec/en-US/google_hotword_clg \
	vendor/explay/Alto/usr/srec/en-US/google_hotword.config:/system/usr/srec/en-US/google_hotword.config \
	vendor/explay/Alto/usr/srec/en-US/google_hotword_logistic:/system/usr/srec/en-US/google_hotword_logistic \
	vendor/explay/Alto/usr/srec/en-US/grammar.config:/system/usr/srec/en-US/grammar.config \
	vendor/explay/Alto/usr/srec/en-US/hmmsyms:/system/usr/srec/en-US/hmmsyms \
	vendor/explay/Alto/usr/srec/en-US/hotword_symbols:/system/usr/srec/en-US/hotword_symbols \
	vendor/explay/Alto/usr/srec/en-US/lintrans_model:/system/usr/srec/en-US/lintrans_model \
	vendor/explay/Alto/usr/srec/en-US/metadata:/system/usr/srec/en-US/metadata \
	vendor/explay/Alto/usr/srec/en-US/normalizer:/system/usr/srec/en-US/normalizer \
	vendor/explay/Alto/usr/srec/en-US/norm_fst:/system/usr/srec/en-US/norm_fst \
	vendor/explay/Alto/usr/srec/en-US/offensive_word_normalizer:/system/usr/srec/en-US/offensive_word_normalizer \
	vendor/explay/Alto/usr/srec/en-US/phonelist:/system/usr/srec/en-US/phonelist \
	vendor/explay/Alto/usr/srec/en-US/rescoring_lm:/system/usr/srec/en-US/rescoring_lm \
	vendor/explay/Alto/usr/srec/en-US/symbols:/system/usr/srec/en-US/symbols

